### ISSUE TITLE
For Mac OS, it takes a while for downloading a video to start.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#101]
**Branch:** master(OS X installer)

**Expected Behavior:** Prompt the user that in Mac OS, downloading a video will take a while to start.

**Current Behavior:** No message telling the user that downloading a video will take a while to start.
That is only for Mac OS.

**Steps to reproduce:**

1. Login as admin
2. Click on `Videos` tab
3. Navigate to the `topic tree` and click the checkbox on the video you want to download.
4. Click on `Download selected video` button.

Notice that downloading a video will not start immediately.

**Comment by cpauya** [comment]
Duplicate of https://github.com/learningequality/ka-lite/issues/3990
