### ISSUE TITLE
Handle errors on click in menu items.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#104]
**Branch**  `master(osx installer)`

**Current Behavior:** Any errors occurred during clicking on `menu items` are not properly handled.
 
Example: If port is currently used and we try to click `Start KA Lite` in the menu like:
![xstart](https://cloud.githubusercontent.com/assets/8664071/8820792/1074359e-308b-11e5-8edb-1510aa38f6a4.png)

The process would fail. The old status was `stopped` and the current would be `stopped` also,  so the effect will be the menus were greyed:
![xconflect](https://cloud.githubusercontent.com/assets/8664071/8820810/37052812-308b-11e5-88ed-53f2430c20a6.png)

**Expected Behavior:** Create a another status like `startingup` so that when conflict in port, the current status will be `startingup`. The menus would work properly.

**Steps to reproduce:** 

1. launch KA Lite Monitor app while the port `127.0.0.1:8008` is used.
2. Enter username and password in preferences dialog and click apply
3. Enter root password.
4. Click Kalite Start menu.

The menus will be greyed even you wait a long while:

![xconflect](https://cloud.githubusercontent.com/assets/8664071/8820878/b8ebe88e-308b-11e5-9144-734f7bbaef7d.png)

**Comment by arceduardvincent** [comment]
Other way to reproduce the issue:
 1. Run the `kalite start`. 
 2. Delete ~/.kalite/kalite.pid
 3. Run the `KA-Lite Monitor` in your Xcode editor this will show the   `KA-Lite Monitor` menu.
 4. Observe that the menus were greyed.

See the image below as demonstration.
![screenshot 2015-07-22 16 35 39](https://cloud.githubusercontent.com/assets/4099119/8821375/c0009e86-308f-11e5-9996-7ecc22cae163.png)

**Comment by cpauya** [comment]
This is initially handled by https://github.com/mrpau/installers/commit/501b310c754c58a353067216b79ef6543b7e0a68 but we need to make a more robust solution to it.

**Comment by djallado** [comment]
I can't replicate this issue on the latest build of KA Lite. We can close this now.
