### ISSUE TITLE
Starting the current devlopment Windows installer provides no user notification on startup

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#107]
OS :  ALL Windows

The installer should provide some immediate notification that the installation or upgrade process is underway to prevent the user from starting the process twice. There is a very long pause between the initial "start" and the fist dialog box that being the python installation. This also dramatically affects windows ka-lite upgrades because in that process the prior installation is uninstalled and having both running out of sync at the same time can cause the system to get stuck trying to both install and uninstall simultaneously.

**Comment by EdDixon** [comment]
This may only be an issue where the user has a previous version of python installed (such as an upgrade) otherwise there is a pretty quick notification that python will be installed.

**Comment by MCGallaspy** [comment]
Do you mean that after launching the installer executable, there is a long pause before anything noticeable happens?

**Comment by MCGallaspy** [comment]
> Do you mean that after launching the installer executable, there is a long pause before anything noticeable happens?

I'd noticed the same thing on some windows virtual machines. There it turned out the problem was a windows service using all the available resources. Stopping that service caused the installer to proceed normally.
