### ISSUE TITLE
Bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#108]
Branch `master`

Current Behaviour : Running the `kalite start` reproduce an issue of `bad interpreter: No such file or directory`

Expected Behaviour : Able to run the `kalite` executable. 

Steps to Reproduce : 
>1. Download the latest build installer in the dungeon server.
>2. Go to the `/Applications/KA-Lite Monitor.app/Contents/Resources/pyrun-2.7/bin`
>3. run ` ./kalite start` 
>4. Notice that `kalite` executable reproduces an error bad interpreter: No such file or directory.

See the image below as demonstration.
![screenshot 2015-07-23 02 15 30](https://cloud.githubusercontent.com/assets/4099119/8833359/b6783cce-30e0-11e5-9d4d-1c92cc89988a.png)

**Comment by cpauya** [comment]
This still fails because all files inside the `pyrun-2.7/bin/` folder has the wrong shebang.  It uses the pyrun path of the build server or the computer that made the build.

Re-opening because this is a blocker for `0.14.x`.

**Comment by cpauya** [comment]
Fixed in #110
