### ISSUE TITLE
Mac Installer UX Suggestion

### ISSUE THREAD

**Issue by whitzhu** [learningequality/installers#114]
1. Add Icon on dock as well, versus just having it on the status bar 
![screen shot 2015-07-23 at 1 31 31 pm-01](https://cloud.githubusercontent.com/assets/12800136/8861573/01be8972-3140-11e5-9dc1-c8bf2f462072.png)

2. Dock Icon opens to another window which there are clear instructions to Turn KA lite on/off and to open KA lite in browser
![2-01](https://cloud.githubusercontent.com/assets/12800136/8862385/177a3ff4-3145-11e5-9d5d-a5364f03b6e0.png)

**Comment by cpauya** [comment]
Hi @whitzhu - this is now implemented in #233.  We didn't have another window yet so when the dock icon is clicked, it shows the Preferences window.

**Comment by benjaoming** [comment]
Hurray, this is fixed :) Great work!
