### ISSUE TITLE
deb installation method fails on Debian install

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#116]
While installing the current (alpha 11) on Debian stable I encountered the following error:

``` 
ed@FLE-Debian:~/Downloads$ sudo dpkg -i ka-lite-bundle_0.14.alpha11-0ubuntu1_all.deb 
Selecting previously unselected package ka-lite-bundle.
(Reading database ... 133644 files and directories currently installed.)
Preparing to unpack ka-lite-bundle_0.14.alpha11-0ubuntu1_all.deb ...
Unpacking ka-lite-bundle (0.14.alpha11-0ubuntu1) ...
Setting up ka-lite-bundle (0.14.alpha11-0ubuntu1) ...
/var/lib/dpkg/info/ka-lite-bundle.postinst: 34: /var/lib/dpkg/info/ka-lite-bundle.postinst: cannot create /etc/ka-lite/username: Directory nonexistent
dpkg: error processing package ka-lite-bundle (--install):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 ka-lite-bundle
```

I suspect the intention here is to use "/etc/ka-lite/ed" causing this error rather than "/etc/ka-lite/username"?

**Comment by EdDixon** [comment]
May be related to issue #116 ?

**Comment by benjaoming** [comment]
definitely a duplicate, no reason to track separately :)

**Comment by benjaoming** [comment]
Thanks for testing, I'll be investigating. It's supposed to be called `/etc/ka-lite/username` and contain the user name of the user running the system service as specified during debconf.

**Comment by EdDixon** [comment]
Not sure which issue is the duplicate, so adding here? I am not finding that folder ```/etc/ka-lite``` in the working install on Debian using the PyPi procedure though? There is instead a .kalite folder in my home user directory that appears to contain the program and contents folders, etc... If that is what the purpose of the ```/etc/ka-lite/username``` folder is meant to contain?

**Comment by benjaoming** [comment]
Sorry, I was looking at the same issue opened in two different tabs :D

**Comment by EdDixon** [comment]
Glad to see it reopened, just encountered the same error message with version a12. However there is a .kalite in my home directory after installation.
```
sudo dpkg -i Downloads/ka-lite-bundle_0.14~a12-0ubuntu1_all.deb 
[sudo] password for ed: 
Selecting previously unselected package ka-lite-bundle.
(Reading database ... 86072 files and directories currently installed.)
Preparing to unpack .../ka-lite-bundle_0.14~a12-0ubuntu1_all.deb ...
Unpacking ka-lite-bundle (0.14~a12-0ubuntu1) ...
Setting up ka-lite-bundle (0.14~a12-0ubuntu1) ...
/var/lib/dpkg/info/ka-lite-bundle.postinst: 34: /var/lib/dpkg/info/ka-lite-bundle.postinst: cannot create /etc/ka-lite/username: Directory nonexistent
dpkg: error processing package ka-lite-bundle (--install):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 ka-lite-bundle
```

**Comment by benjaoming** [comment]
@EdDixon 

Thanks for following up on this!

Which Debian / Ubuntu are you seeing this on? I can't recreate it installing ka-lite-bundle on Ubuntu 15.04 -- on the other hand I managed to find another problem #124.

I am currently on a break but will have a look at it Sunday and Monday. Please do continue testing on other platforms in case it's relevant.

**Comment by benjaoming** [comment]
This should be resolved in beta1.

**Comment by EdDixon** [comment]
Definitely confirmed resolved in bundle_0.14.0ubuntu1_all Thanks,
