### ISSUE TITLE
KA-Lite Monitor first launch is taking a long time.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#120]
**Branch:** `MAster` (OSX Installer)

**Expected Behavior:** Not taking a long time when clicking on `Apply` button in `Preferences dialog`.

**Current Behavior:** It's taking a long time when clicking on Apply button in preferences dialog.

**Steps to reproduce:** 

1. Launch KA-Lite Monitor app.
2. Click `Apply` in preferences dialog, another dialog box will appear asking your password type a password and click `Ok`.

![screen shot 2015-07-30 at 10 50 44 am](https://cloud.githubusercontent.com/assets/8664071/8974819/f88c6806-36a8-11e5-9770-74e84a016417.png)
3. Another dialog box will appear prompting the user to wait, click on `Ok` button.

![conferm](https://cloud.githubusercontent.com/assets/8664071/8974655/d020f58c-36a6-11e5-9a93-b3a7f80bcbcb.png)
After clicking on the `Ok` button, it will make you wait 25 seconds before the `KA-Lite Monitor` menus become available
4. Click on `Start KA-Lite` menu. 

![start ka-lite](https://cloud.githubusercontent.com/assets/8664071/8974683/20e3442a-36a7-11e5-9e3a-5cb13e51f158.png)
After clicking on `Start KA-Lite` menu, it will make you wait 40 seconds before you can click the other menus.

@EdDixon, I tested this at the latest build: `KA-Lite-Monitor.dmg-2015-07-29b.zip`.  Please test this also if it the same at your end.

**Comment by EdDixon** [comment]
Yes it was my understanding that there are performance related git issues
open already but I can verify that there are performance related issues as
late as day 7/29 in the develop MAC installer and those seem to be carrying
over to the app itself. I have been waiting to see if there is a central
cause for this as it has not been an issue before before flooding with
specific issues but areas affected are the installation process as
described, The video and language pack progress bars, and just user
interaction in general?


Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE, Support FLE via Amazon Smile!
<https://learningequality.org/donate/>
M (575)-636-9549

**Comment by aronasorman** [comment]
Moved to 0.15.

**Comment by cpauya** [comment]
We've fixed this for the upcoming 0.16 release.  We've reduced the startup time to a few seconds only!

Check-out the `develop` branch for the fixes.
