### ISSUE TITLE
Reboot is required after OSX installation.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#121]
**Branch:** `Master` (OSX installer)

**Expected Behavior:** No need to reboot the machine after installation.

**Current Behavior:** Reboot is required after OSX installation.

**Steps to reproduce:**

1. Install the `KA-Lite Monitor` app.
2. Launch `KA-Lite Monitor`.
3. Click Apply in preferences dialog, another dialog box will appear asking your password type a password and click `Ok`.

![screen shot 2015-07-30 at 10 50 44 am](https://cloud.githubusercontent.com/assets/8664071/8977470/2d822b2c-36cc-11e5-9ff3-6abf9570bebe.png)
4. Another dialog box will appear prompting the user to wait, click on `Ok` button.

![conferm](https://cloud.githubusercontent.com/assets/8664071/8977522/8b9dae0c-36cc-11e5-9846-94ea1abe98dc.png)
5. Click on `KA-Lite logo` to see the menu items.

![start ka-lite](https://cloud.githubusercontent.com/assets/8664071/8977504/64cfb75c-36cc-11e5-8c42-132450b6b9e7.png)
*To make it work properly you have to reboot your machine.*

@EdDixon Kindly check this issue if the same as you tested in this build: `KA-Lite-Monitor.dmg-2015-07-29a.zip`. I also replicated that issue at the same build. I also reboot my machine to make it work properly. 

So far at the latest build `KA-Lite-Monitor.dmg-2015-07-29b.zip`, no need to reboot the machine after installation to make it work properly. @EdDixon, kindly test it if it works properly after installation that you don't have to reboot your machine.

**Comment by arceduardvincent** [comment]
Hi @djallado I try to replicate the issue and it seems the problem doesn't manifest at all.
I think it is fixed already.

**Comment by djallado** [comment]
This issue is no longer exists with the latest build. I'm going to close this.
