### ISSUE TITLE
Windows - assessment items not available immediately after installation

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/installers#123]
Using the windows installer, assessment items (and potentially other resources) may not be available immediately after installation. This is because the installer updates an environment variable (`KALITE_ROOT_DATA_PATH`), but other applications are not made aware of this change until the installer exists. In particular, it's possible to launch the app _before_ the installer exits (there's a checkbox on the last page of the wizard), in which case it will not be aware of the updated environment,

Exiting and restarting the task-tray program should make assessment items appear available, as will restarting the computer -- then all applications will be aware of the updated environment.

**Comment by radinamatic** [comment]
This is confirmed with the latest Windows installer from the `bug bash` doc, on Win XP, 7 & 8:

- If the user launches KA Lite on from the installer, by leaving the checkbox on the last install page of the wizard `on` (it is `on` by default), the majority of assessment items & the documentation link in the user menu will not be available. 

- If the user does NOT start KA Lite from the wizard, but from the sys tray program all assessment items & the documentation link are available at start.

**Comment by MCGallaspy** [comment]
Seems like the quickest resolution would be to force restart after installation, and remove the ability to launch the app from the wizard.
