### ISSUE TITLE
Run `kalite manage compileymltojson` when building the installer.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#126]
**Branch** 0.14.x

**Expected Behavior** The `setup.sh` script must run `kalite manage compileymltojson` when building the installer to prevent issues like learningequality/ka-lite#4174.

**Current Behavior** Clicking on the device management page link causes an error `no module named yaml` as per learningequality/ka-lite#4174.

**To reproduce**
* Install the latest OSX Installer "KA-Lite-Monitor.dmg-2015-08-07a.zip"
* Login to the ka-lite web app as admin and go to Manage -> Facilities tab.
* Click on the device name link.
* Notice the `ImportError: No module named yaml` error on the page.

**Possible Solution/s**
* As per @aronasorman - we can "temporarily install `pyyaml`, run `compileymltojson`, then uninstall `pyyaml`" when running `setup.sh`.

**Comment by radinamatic** [comment]
I wonder why this sounds like the issue I had on Windows 8 but not on XP (#4101)...

**Comment by benjaoming** [comment]
Pre-built JSON is part of the PyPi distribution since beta 1 if that helps?
