### ISSUE TITLE
OSX application performance issues.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#129]
**Branch** master

**Target** 0.15.x

**Expected Behavior** The application should be responsive and handle calls to the `kalite` executable in a non-blocking way.

**Current Behavior** Calls to the `kalite` executable use the blocking `system` function.

Examples

1. When the `Apply` button is clicked, the app runs `kalite manage setup` which could take a long time.  This makes the user wait for about a minute or two and shows the "beach ball" mouse cursor which gives the impression that the app has "frozen".
2. We check the status of the `kalite status` to show the appropriate icon on the system menu bar.  This could manifest a "mini-freeze" while the command is being run.

**Possible Solution/s** Use the [NSTask](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSTask_Class/index.html) class.

Since this is going to be a non-blocking call, we must somehow show the user an indicator that something is being run on the background.  Then hide that after the processing is done.

**Functionalities to check**

* [ ] Use `NSTask` class instead of the `system` function.
* [ ] Set the `KALITE_PYTHON` environment variable and point it to the `pyrun` binary for every call to `NSTask`.  This makes sure that calls like `kalite status` will work and not crash the app.
* [ ] Show an indicator (progress bar, etc) during run of command.
* [ ] Show the logs / output of the `kalite` command in the GUI or Console app.

**Related Issues**
* [KA-Lite Monitor first launch is taking a long time.](https://github.com/learningequality/installers/issues/120)

**References**
* [StackOverflow's - Execute a terminal command in a Cocoa app](http://stackoverflow.com/questions/412562/execute-a-terminal-command-from-a-cocoa-app)
* [NSTask Tutorial for Mac OS X](http://www.raywenderlich.com/36537/nstask-tutorial)

**Comment by amodia** [comment]
@cpauya this are the updated Functionalities checklist of the kalite osx app.

**Functionalities to check**

- [x] Use NSTask class instead of the system function.
- [x]  Set the KALITE_PYTHON environment variable and point it to the pyrun binary for every call to  
NSTask. This makes sure that calls like `kalite status` will work and not crash the app.
- [ ]  Show an indicator (progress bar, etc) during run of command.
- [X]  Show the logs / output of the kalite command in the GUI or Console app.

**Comment by cpauya** [comment]
Nice @amodia - we can open a new issue for the indicator if need be.  I think you are showing a "processing" image during run of command so that will suffice for now.
