### ISSUE TITLE
Provide user a way to "force" start ka-lite.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#13]
**Branch** \<feature branch\>

**Expected Behavior**  We use the `bin/kalite status` command to monitor the status of ka-lite to update the menu/icon.

**Current Behavior / Problem**
The user cannot recover from the OS X app if result of `bin/kalite status` returns an abnormal value like one of the following:
* 7: 'Unclean shutdown',
* 9: 'KA Lite server configuration error',
* or perhaps any other abnormal values

**To Reproduce**

1. Manually trigger the issue
    * Run `touch ~/.kalite/kalite.pid`
    * Run the .app

2. Run the .app and quit it in Activity Monitor, it should leave those .pid files open.

3. On the Console, you should see something like

```bash
Invalid PID file (100)
2015-02-10 08:00:19.643 KA-Lite Monitor[23203:1977020] Has encountered an error, please check the Xcode terminal or the Console:
2015-02-10 08:00:19.643 KA-Lite Monitor[23203:1977020] FOUND local_settings.py!
2015-02-10 08:00:19.644 KA-Lite Monitor[23203:1977020] FOUND database!
2015-02-10 08:00:19.644 KA-Lite Monitor[23203:1977020] KA Lite is now loaded.
2015-02-10 08:00:36.836 KA-Lite Monitor[23203:1977020] Stopping and quitting the application...
Already stopped. Status was: Invalid PID file
2015-02-10 08:00:37.156 KA-Lite Monitor[23203:1977020] Fetching `bin/kalite status`...
Invalid PID file (100)
```
(see screenshot below)
![screenshot 2015-02-10 08 01 55](https://cloud.githubusercontent.com/assets/175580/6118766/02ce9aa6-b0fc-11e4-88a5-9fb293424617.png)

**Possible Solution/s**
1. Provide a button on the UI to "restart" the application; Or;
2. Modify the Setup button at the Advanced tab to "clean" those .pids and restart the application.

**Related Issues**
* https://github.com/learningequality/ka-lite/issues/2991

/cc: @aronasorman @djallado @amodia

**Comment by benjaoming** [comment]
Hi @cpauya thanks for the report!! This problem is IMO already described in learningequality/ka-lite#2919 and will be fixed shortly, and I agree about the solution.

I'm thinking that the optimal behaviour would be:

    kalite stop
    Error: kalite not responding
    Forcing PID XXX top stop
    stopped

Same process for restarting.

**Comment by cpauya** [comment]
Ah, thanks for that @benjaoming. 

For the meantime, in case we encounter this, we will check `~/.kalite/` for any `.pid` or `.lock` files and try to remove those then restart the app.

**Comment by benjaoming** [comment]
Remember to kill the old process, too.. I guess you will have some errors of the port being used in case you don't :) Sorry for the inconvinience.

**Comment by cpauya** [comment]
Ah yes, and make sure to search for `pyrun` or `python` on the process list (Activity Monitor of mac).  Good point. :)
