### ISSUE TITLE
Subsequent video downloads do not work on OSX.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#134]
**Branch** 0.15.x
**Target** master

**Expected Behavior** Downloading videos one after another must work.

**Current Behavior** Downloading another video after a successful video download does not work.

**Screenshots**

Here's the first attempt to download a video, it has 3 pyrun processes.
![screenshot 2015-08-14 14 55 09](https://cloud.githubusercontent.com/assets/175580/9268805/22be32ec-4295-11e5-9a57-1c68dc2c198c.png)

After waiting for about 30 seconds, we only have 1 pyrun process and the video download did not start.
![screenshot 2015-08-14 14 55 52](https://cloud.githubusercontent.com/assets/175580/9268781/ec4ff29a-4294-11e5-9938-dec94254ef37.png)

**To reproduce**

1. Delete the `~/.kalite/` folder if it exists.
1. Install latest OSX Installer from dungeon.
1. Launch `Activity Monitor` app and filter it with "py".
1. Launch the app, do the setup, start the server, and navigate to the site in the browser.
1. Login as the admin user, do a one-click device registration, then download a video.
1. After the first video download has finished, download another video.
1. After about 30 seconds, notice on `Activity Monitor` that there is only one `pyrun` process and that the video download did not start.

**Comment by aronasorman** [comment]
This seems critical, and might be worth having this fixed ASAP.

**Comment by cpauya** [comment]
Got it @aronasorman  - we are working on this today.

**Comment by djallado** [comment]
@cpauya, I tested the issue using source branch `0.14.x` and I observed that second download will work if the subprocess for download will exit. After I downloaded the video I checked the `Activity Monitor` just to know the python processes.

If I download a video there are 4 python processes in my `Activity Monitor`, here's the snapshot:
![screen shotpythondownload](https://cloud.githubusercontent.com/assets/8664071/9303947/8ca0a2ee-4515-11e5-9e3a-67d5cb5045f1.png)

If I download again the video without finishing the subprocess, this will not work.
But if I waited it to exit, the next download will work. Looking at the `Activity Monitor` the python process now become 3, Here's the snapshot:
![screen shotpython ready](https://cloud.githubusercontent.com/assets/8664071/9304115/4e4d1c46-4517-11e5-8fa8-e20126c9a747.png)
 The next download will work properly.

**Comment by djallado** [comment]
I tested `KA_Lite-0.14.0-beta3.dmg` from https://learningequality.org/downloads/ka-lite/0.14/installers/mac/.
 
The second download will work properly if I wait 2 `pyrun` processes to exit. 
Approximate time to wait is about 25 second before that 2 processes will exit.

The screen shot below shows that the download has been completed in the browser but the processes in the `Activity Monitor` is not been finished.
![screen shot 2015-08-18 at 10 21 37 am](https://cloud.githubusercontent.com/assets/8664071/9348283/d86ae782-4666-11e5-853e-549f218855e1.png)
If you try to download again the video, this will not work. But it two processes of pyrun will exit, the next download will work.

**Comment by djallado** [comment]
This issue also manifest in the Windows installer, here's the screenshot below:
![untitled](https://cloud.githubusercontent.com/assets/8664071/9382778/438ba848-4776-11e5-97af-cc7366422ed7.png)
 After a first successful download, I tried to download another video, but it doesn't work. I waited for more than five minutes and nothing happened.

**Comment by aronasorman** [comment]
This might be more appropriate for the kalite repo then. Can you try replicating this on a dev repo? I'll try it here as well.

**Comment by djallado** [comment]
@aronasorman, I updated my `ka-lite` repository, and I observed that the subsequent video download will work. The new update on `ka-lite` repository solved the issue  but when we build new mac installer using `setup.sh`, the issue still manifest in the mac installer.

Workaround on the issue.
After a successful video download, reload the page to download another video, or download all the desired video you want to download.

**Comment by cpauya** [comment]
Here are some interesting findings about video downloads on OSX using only the command-line:

I have the following set up:

1. I used a built OSX app (not running).
2. `kalite` on `/usr/bin/kalite`
3. `ka-lite` repo for this test points to the `0.14.x` branch
4. I only have this environment variable:

    KALITE_PYTHON=/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/bin/pyrun

Then I tried to run this snippet under `kalite manage shell` on OSX:

```python
import shlex, subprocess
cmd = "kalite manage videodownload --commandline"
args = shlex.split(cmd)
subprocess.Popen(args)
```

And here's the output (row spaces are for readability):

```bash
cyril-lappy6:osx cyril$ kalite manage shell
Python 2.7.9 (default, May  9 2015, 00:17:45)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
### A. I have 2 pyrun processes on Activity Monitor.

>>> import shlex, subprocess
>>> cmd = "kalite manage videodownload --commandline"
>>> args = shlex.split(cmd)
>>> subprocess.Popen(args)
<subprocess.Popen object at 0x1049bc4d0>
>>> Nothing to download; exiting.
INFO:kalite:Downloaded 0 of 0 videos successfully.
INFO:kalite:Preloading exercise data for language en.
### B. ==> I now have 4 pyrun processes.  Waited a minute for the next message below to appear.

### C. ==> I only have 2 pyrun processes.
INFO:kalite:Preloading content data for language en.
INFO:kalite:Preloading topic tree data for language en.
### D. ==> Had to press <Enter> here so it goes back to the python prompt.

>>>
```

Perhaps the output could help explain the reason/s why we are having these "delays" during video downloads on OSX?

**Comment by cpauya** [comment]
This is already fixed on the latest `develop` branch.
