### ISSUE TITLE
Shebang checker corrupts the kalite executable.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#135]
**Branch** master

**Target** 0.14.x

**Expected Behavior** Shebang check should not corrupt the executables at the `<application-folder>/Contents/Resources/pyrun-2.7/bin/` folder.

**Current Behavior** When the .app is run, it checks the shebangs of the executables at `<application-folder>/Contents/Resources/pyrun-2.7/bin/` folder but corrupts the `kalite` executable.

**To reproduce**

1. Download the latest OSX installer from the dungeon server.
1. Install the .dmg and open the `kalite` executable at `<application-folder>/Contents/Resources/pyrun-2.7/bin/` folder.  Notice the format.

    ```bash
    #!/opt/bamboo_data/xml-data/build-dir/KL-KALITE014-OSX/installers/osx/temp/pyrun-2.7/bin/pyrun
    # EASY-INSTALL-SCRIPT: 'ka-lite==0.14.0',u'kalite'
    __requires__ = 'ka-lite==0.14.0'
    __import__('pkg_resources').run_script('ka-lite==0.14.0', u'kalite')
    ```
    
1. Run the .app and then check the `kalite` executable again at previous step.
1. Notice that it has changed in format.

    ```bash
    #!/Applications/KA-Lite-Monitor.app/Contents/Resources/pyrun-2.7/bin/pyrun
    # EASY-INSTALL-SCRIPT: 'ka-lite==0.14.0',u'kalite'
    __requires__ = 'ka-lite==0.14.0'
    __import__('pkg_resources').run_script('ka-lite==0.14.0', u'kalite')
    0.14.0', u'kalite')
    ```

The issue is the extra **0.14.0', u'kalite')** on the last line.

/cc: @aronasorman

**Comment by djallado** [comment]
@cpauya. I verified this using build [236](http://dungeon.learningequality.org:8085/browse/KL-KALITE014-236/artifact)

I installed the `.dmg` and checked the `kalite` executable.
Here's the snapshot:
![before](https://cloud.githubusercontent.com/assets/8664071/9270988/a83809da-42a8-11e5-9ab1-da8c7aee187c.png)

After checking it, I run the app and checked again the `kalite` executable.
Here's the snapshot:
![after](https://cloud.githubusercontent.com/assets/8664071/9271008/e3e935ee-42a8-11e5-8690-20c45e7ecd15.png)

**Comment by cpauya** [comment]
The reason for this is that the replaced string is longer than the replacement, thus the "remaining" file contents persists.
