### ISSUE TITLE
Raspberry Pi settings module import issue

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#138]
@aronasorman reported

> @benjaoming ok kalite shell is running now, I needed to install pkg-resources and setuptools, i think they weren't pulled in or shown as dependencies though, can you add that?

Adding these as dependencies and reporting back when the package is updated.

Manual work-around:

    sudo apt-get python-setuptools

**Comment by benjaoming** [comment]
Fixed in ka-lite-raspberry-pi_0.14~b3-ubuntu6

@EdDixon could you try it out? Here are the instructions, please comment in here if they need adjustments:

```bash
# Be root
sudo -i

# Install apt-apt-repository and use it to add the learningequality PPA
apt-get install -qy software-properties-common python-software-properties
apt-add-repository -y ppa:learningequality/ka-lite

# Replace 'raspbian' dist name, because it doesn't exist, and trusty's packages are the same
sed -i 's/raspbian/trusty' /etc/apt/sources.list.d/learningequality*

# Update package db
apt-get update

# Install package in silent mode
DEBIAN_FRONTEND="noninteractive" apt-get -qy install ka-lite-raspberry-pi
```

**Comment by alejacquet** [comment]
Hey guys,

At least for the Minian version (2015-02-18-wheezy-minibian.img). I had to edit the learningequality-ka-lite-wheezy.list from WEZZY to TRUSTY
/etc/apt/source.list.d/ka:/etc/apt/sources.list.d# cat learningequality-ka-lite-wheezy.list
deb http://ppa.launchpad.net/learningequality/ka-lite/ubuntu trusty main 
deb-src http://ppa.launchpad.net/learningequality/ka-lite/ubuntu trusty main 

Using this I was able to install the ka-lite-raspberry-pi

**Comment by benjaoming** [comment]
@alejacquet you're right, it's this particular line that was tailored for raspian, that would have to be changed:

```bash
# Replace 'raspbian' dist name, because it doesn't exist, and trusty's packages are the same
sed -i 's/raspbian/trusty' /etc/apt/sources.list.d/learningequality*
```

**Comment by alejacquet** [comment]
Yes, the sed command is sed -i 's/wheezy/trusty/g' /etc/apt/source.list.d/learningequality*

**Comment by benjaoming** [comment]
It seems we no longer have the settings module import bug, closing this.
