### ISSUE TITLE
Previous user can login even after resetting the app.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#139]
**Branch:** `Master(OSX installer)`

**Expected behavior:** After the `Reset App` old account will not be able to login. 

**Current Behavior:** The previous user can login even after performing the `Reset App`.

**Steps to reproduce:**

1. Launch `KA-Lite` app
2. Click on `KA-Lite` logo at menu item
3. Choose `Preferences`
4. `KA-Lite Preferences` dialog will appear, click on `Advanced` tab.
5. Click on `Reset App` button, confirmation dialog will appear click on `Ok`, then another dialog will prompt you asking your `password`. 
6. Click on KA-Lite logo again in menu item.
7. Choose `Preferences`.
8. In the `Preferences` tab, specify your username and password and then click `Apply`.
9. Another dialog will appear asking your password.
10. Start KA-Lite Monitor. *Note that processing will take few seconds.*
11. Load KA-Lite in browser.
12. Login using the previous account.

*Note that the previous account can still login.* 

/cc: @EdDixon and @aronasorman

**Comment by aronasorman** [comment]
This was due to the session now being stored entirely in the browser. The easiest solution here is in https://github.com/learningequality/ka-lite/pull/4257.

**Comment by cpauya** [comment]
This issue has been fixed in #277.  We now remove creation of admin account from within the .app.
