### ISSUE TITLE
Implement Mac Packages

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#144]
**Branch**  `master`

**Target** `0.15.x`

**Proposal Description**
To use [Packages](http://s.sudre.free.fr/Software/Packages/about.html) project in our `KA-Lite Monitor` and able to create a configurable installer. As of now we are using the [create-dmg](https://github.com/mrpau/create-dmg) project which we can't configure. 

**Checklist**
- [x] Able to display the `README` and `License`
- [x] Able to create a configurable installer.
- [x] Modify `setup.sh`
- [x] Update `README`

The image below demonstrates the use of  [Packages](http://s.sudre.free.fr/Software/Packages/about.html).
![screenshot 2015-08-26 13 01 47](https://cloud.githubusercontent.com/assets/4099119/9485906/aacc62f6-4bf2-11e5-9f95-8abae308284c.png)

**Comment by aronasorman** [comment]
That looks much better :)

**Comment by arceduardvincent** [comment]
Hi @aronasorman my branch #147 is ready for testing.

**Comment by cpauya** [comment]
Fixed in #245.
