### ISSUE TITLE
KA-Lite documentation for Mac installer is not available

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#150]
**Branch:** master

**Expected Behavior:**  Able to show the documentation link in the Navbar.
![8edubpc](https://cloud.githubusercontent.com/assets/4099119/9657849/4c01d8ec-5277-11e5-9572-daa4305f3da7.png)

**Current Behavior:**  The documentation  link was not available.  

**Steps to reproduce:**
>1. Run the  KA-Lite-Monitor 
>1. Navigate the KA-Lite Monitor icon in the system tray, then click start `KA Lite`
>1. Wait till `Open in a Browser` is clickable, then click it.
>1. Navigate to the KA Lite application in the browser 
>1. Navigate to `Login` tab  then login to your account.
>1. Beneath in the account  tab notice that the `Documentation` is not available.

See image below as demonstration
![screenshot 2015-09-03 19 43 37](https://cloud.githubusercontent.com/assets/4099119/9657494/20843d84-5274-11e5-9aa5-48ee4e3876c4.png)

**Comment by cpauya** [comment]
@arceduardvincent I don't see the "Documentation" link upon testing this with the `./setup.sh "https://github.com/learningequality/ka-lite/archive/0.15.x.zip"` command.

Will re-open this now and please double-check @arceduardvincent.

**Comment by cpauya** [comment]
This is already fixed on the latest master branch, closing.
