### ISSUE TITLE
Kalite will use the latest version of python installed rather than the bundled version

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#152]
While testing the 0.14.0 windows installer on Windows version 10 I encountered an issue with the server not starting after installation. Further testing revealed that the kalite command was not using the bundled 2.7.x version of python but a newer version (3.4.x) which was installed prior to the test. The screenshot shows the error and where it seems to "hang". 

As a quick check to determine the cause and potentially affected versions @MCGallaspy had me set the KALITE_PYTHON variable to the 2.7 version which then did allow the kalite command to proceed and start the server within that same shell instance (NOTE THIS IS NOT A PERMANENT FIX FOR THIS PROBLEM JUST A TEST TO GATHER MORE INFO ON THE CAUSE) . After consulting @MCGallaspy who has been doing the majority of the windows installer development we feel this issue likely affects all versions of windows with Python 3 installed. 
![pythonversionerror](https://cloud.githubusercontent.com/assets/4349806/9669548/35a11af4-5245-11e5-8c69-a6730b01d8a9.png)

**Comment by MCGallaspy** [comment]
Perhaps the resolution here is to raise an error if the wrong version if python is used.

**Comment by MCGallaspy** [comment]
Fixed in https://github.com/learningequality/ka-lite/issues/4445

**Comment by MCGallaspy** [comment]
Now the application will complain and advise the user to set KALITE_PYTHON, if python version 3 is detected.
