### ISSUE TITLE
Stop server does not stop the server from systray icon

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#16]
Selecting stop server from the systray icon options in 0.13 does not stop the server. This is made worse by the fact that the popup closes once the option has been selected hiding the fact that the server is still running. On subsequent checks from the same icon you will see that the server is not in the stopped state.

**Comment by cpauya** [comment]
Hi @EdDixon - I assume this is on Windows?  I'm curious because this repo has three (debian, osx, windows) folders for the installer sources. :)

**Comment by aronasorman** [comment]
@cpauya yup, for Windows :)

**Comment by EdDixon** [comment]
This has been an intermittent problem and I have discovered that by shutting down (actually stopping the supporting python processes) and then restarting the server through the systray icon it behaves as designed. I have also noticed when it happens the server had started automatically from booting and not from use interaction with the systray icon or in XP the dialog box. I feel this may be pointing to a permissions issue on who actually controls the process with the automatic launch process overriding the users permission to stop it.

**Comment by MCGallaspy** [comment]
> I feel this may be pointing to a permissions issue on who actually controls the process with the automatic launch process overriding the users permission to stop it.

Seems plausible.

**Comment by EdDixon** [comment]
I was able to confirm that the python processes supporting the server are running under system permissions when started via the windows startup option. This may be an issue on other platforms less tested so I will check those as the builds become available in the latest 13.x branch.

**Comment by MCGallaspy** [comment]
@EdDixon are you experiencing this issue only on XP? Or other versions of Windows as well?

**Comment by EdDixon** [comment]
Also WIn7

**Comment by EdDixon** [comment]
In fact that was the system I confirmed the permissions under replicate by running from boot and looking at task manager python processes.

**Comment by EdDixon** [comment]
Just a reminder this bug still exists across all windows versions and has been confirmed to be a permissions based issue where the process is running under windows system permissions on launch preventing the user from stopping it. It has been deemed a non blocker for 13.x and many should consider it a feature who would want to stop a perfectly working KA-Lite instal with all this great stuff anyway right?

**Comment by EdDixon** [comment]
Update: this problem also exists when the server is started manually from the gui and not "on boot" as was previously suspected to be the problem on my windows 10 preview here anyway which was the only testing machine not setup to run from boot. I will test other versions to see if this is true across the entire platform or only newer versions of windows and report back.
