### ISSUE TITLE
Progress bar is not showing when downloading a video.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#164]
**Branch:** `Master`

**Current Behaviour:** When downloading a video, the progress bar will not show until the video download is done.

**Expected Behaviour:** Progress bar must be shown when the video download starts.

**Step to Reproduce:**

1. Login as admin.
1. Click on video tab, and select a video you want to download in the topic tree.
1. Click on `Download` button.

**Screenshot**:

![screen shot 2015-09-11 at 5 46 02 pm](https://cloud.githubusercontent.com/assets/8664071/9812011/1a762e54-58ad-11e5-8e3e-d05dbadc691d.png)

In the screenshot, the progress bar will not show until video download is done.

**Comment by cpauya** [comment]
@djallado Which browser/s did you test this with?  Can you try with other browsers if this issue exists too?

**Comment by djallado** [comment]
@cpauya, I used Google Chrome and Safari.

**Comment by cpauya** [comment]
I believe this should be filed on the https://github.com/learningequality/ka-lite/ repo - please test on Firefox too.

**Comment by MCGallaspy** [comment]
Agree with @cpauya.
