### ISSUE TITLE
No indicator in the topic tree for a specific video after a successful download.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#166]
**Branch:** `Master`

**Current Behaviour:** After a successful download of a video, the indicator is not shown in the topic tree for that specific video download.
![screen shot 2015-09-10 at 5 49 02 pm](https://cloud.githubusercontent.com/assets/8664071/9812772/4d8cfc28-58b2-11e5-9df1-15e1e1646c12.png)

**Expected Behaviour:** The indicator must be shown after a successful video download.

**Step to Reproduce:**

1. Login as admin.
2. Click on Video tab, and select a video you want to download in a topic tree.
3. Click on Download new selected video button.

**Comment by cpauya** [comment]
Moved to learningequality/ka-lite#4429
