### ISSUE TITLE
MAC 0.15 dev, assets are not compiled

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#169]
Landing page after installation and subsequent reloading of application and server. Assets are not compiled. No way to login? 

![2015-09-15_12-01-17](https://cloud.githubusercontent.com/assets/4349806/9886094/d5989730-5ba5-11e5-9dd1-d0ccf56584b4.png)

**Comment by cpauya** [comment]
Thanks for reporting this @ed - I remember seeing this last August.  We will work on this today.
