### ISSUE TITLE
0.13 --> 0.15: UI for downloading videos on Windows is buggy

### ISSUE THREAD

**Issue by jtamiace** [learningequality/installers#173]
This happens from installing 0.15 over 0.13 on Windows. I can no longer see the checkbox or "+" that allows you to see deeper into the video hierarchy

![video download](https://cloud.githubusercontent.com/assets/6668144/10027497/2949ce82-611c-11e5-81e2-1e6b3f2522bc.PNG)

**Comment by MCGallaspy** [comment]
Okay, it may have been fixed on `0.15.x` already, as I had encountered the same issue running from source. Can you indicate which installer you used?

**Comment by aronasorman** [comment]
Might just be a matter of running collectstatic again.

**Comment by jtamiace** [comment]
It seems that videos downloaded is retained, though

**Comment by jtamiace** [comment]
I used the ones that were posted on the trello card

0.15: http://field.learningequality.org/KALiteSetup-0.15.0.exe
0.13.2 patch: https://learningequality.org/downloads/ka-lite/

**Comment by MCGallaspy** [comment]
> 0.15: http://field.learningequality.org/KALiteSetup-0.15.0.exe

Okay, for my reference this was uploaded on 9/17

**Comment by jtamiace** [comment]
@MCGallaspy did you make another windows installer since then?

**Comment by MCGallaspy** [comment]
Yeah, I decided it would be a good idea to start dating them: http://field.learningequality.org/KALiteSetup-0.15.0--9-18-2015.exe

If you can test that one out, that'd be great. But I'm not sure if that one is recent enough to incorporate the fix, either.

**Comment by MCGallaspy** [comment]
My plan is to create another one, and then I'll see if I can replicate -- if I can't I'll ask you to try again.

**Comment by jtamiace** [comment]
not sure if this also has to do with the collectstatic issue but this was a recurring issue for exercise images, which also didn't display on this version of the 0.15 installer. commenting here for @rtibbles 

![exercises not showing](https://cloud.githubusercontent.com/assets/6668144/10031714/9f349c0a-6133-11e5-9002-174042ef0383.PNG)

**Comment by MCGallaspy** [comment]
Building another installer to attempt to replicate.

**Comment by MCGallaspy** [comment]
Seems to have been an issue in the app, not the installer -- unable to replicate after updating app and building a new installer. I'm hosting it here for now: http://field.learningequality.org/KALiteSetup-0.15.0--9-25-15.exe
