### ISSUE TITLE
No icon appearing in Windows app menu for 0.15 installer

### ISSUE THREAD

**Issue by jtamiace** [learningequality/installers#175]
@MCGallaspy Very minor issue, but just putting it up here.

![no icon](https://cloud.githubusercontent.com/assets/6668144/10060415/8b8be74e-6205-11e5-95be-a101d0a4d0ef.png)

**Comment by amodia** [comment]
It's the same behavior on `IE10 windows 7` the Kalite executable has no icon assigned.

![screen shot 2015-09-24 at 12 56 24 pm](https://cloud.githubusercontent.com/assets/8663934/10065647/b46ae474-62bb-11e5-93ca-2939245c2620.png)
