### ISSUE TITLE
Static files are not loaded in IE8 on Win7

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#177]
**Branch:** `0.15.x`.

**Windows installer:**  `kalite-setup-0.15.0--9-18-2015.exe`

**Platform:** `IE8 on XP`

**Expected Behavior:** Must load static files.

**Current Behavior:** Static files are not loaded.

**Steps to reproduce:**

 1. Download windows installer at http://field.learningequality.org/KALiteSetup-0.15.0--9-18-2015.exe.
 2. Install it in `IE8 on Win7`.
 3. Launch KA-Lite apps
 4. Click on `Start on Server` in menu option.
 5. Wait until the `Load in browser` menu becomes available and click on it.

**Screenshot:**

![staticinie87](https://cloud.githubusercontent.com/assets/8664071/10064368/3fd77ebc-62aa-11e5-98e3-8b0cc027d366.png)

**Comment by MCGallaspy** [comment]
Let's consolidate this with #176.
