### ISSUE TITLE
Windows Installer should unistall prior version during upgrade phase 

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#18]
During upgrade testing it was found that the 13.x installer acknowledges the prior versions installation and asks the user if they wish to upgrade however at that point does not uninstall the prior version to allow it to be successful breaking 13.x usage of the program.

**Comment by MCGallaspy** [comment]
Broken in what way?

**Comment by EdDixon** [comment]
Front page layout and formatting prevents me from using it it to determine other ways it may be broken see issue 3501 in the ka-lite repo.

**Comment by ruimalheiro** [comment]
This was fixed with PR #19
