### ISSUE TITLE
MAC installer not providing assessments to users

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#181]
On current 0.15 develop testing the MAC installer is not providing assessments to the users in the sidebar (admin or student) even after a restart of the server. This is a new issue that did not exist in the last build. @cpauya 

![2015-09-25_15-00-09](https://cloud.githubusercontent.com/assets/4349806/10112623/fb5e738a-6399-11e5-8eb1-63dbacc1f89b.png)

**Comment by EdDixon** [comment]
Plot thickens, only topics where video has been downloaded seem affected?
![2015-09-25_21-50-54](https://cloud.githubusercontent.com/assets/4349806/10115701/b736f886-63cf-11e5-9791-42699c14969c.png)

**Comment by rtibbles** [comment]
Just to confirm that I am not seeing this issue with Git install on Ubuntu, so probably a Mac only issue.

**Comment by cpauya** [comment]
@ed We've tested the "KA-Lite-Monitor-0.15.0--2015-09-25a.dmg.zip" installer on our local machines and so far all assessment items are displayed on the sidebar.  The greyed-out items are videos that were not downloaded yet.  I have attached a screenshot.
![screenshot 2015-09-28 12 50 08](https://cloud.githubusercontent.com/assets/175580/10128538/a3b97dce-65e6-11e5-9f69-050845be6ee0.png)

@ed Can you try a clean install?  (backup or delete the `~/.kalite/` folder also?)

**Comment by cpauya** [comment]
I found a missing exercise entry "Coin flip sequences" on the sidebar using the latest "KA-Lite-Monitor-0.15.x--2015-09-28a.dmg.zip" OSX installer.

I'm not sure if this is the fault of the installer or that it is simply missing from it's `assessment.zip` taken from https://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip.

![screenshot 2015-09-28 22 45 35](https://cloud.githubusercontent.com/assets/175580/10138876/ff921b3c-6632-11e5-97cb-dfd472fdc106.png)

I've really been bugged by @EdDixon's issue re "only topics where video has been downloaded seem affected"... but I found no way to reproduce it today... maybe tomorrow I'll be lucky. :smile_cat: 

/cc: @aronasorman

**Comment by aronasorman** [comment]
Let's reopen this if @cpauya and co. can reproduce. @cpauya maybe try clearing your .kalite folder?

**Comment by cpauya** [comment]
I did clear the `~/.kalite/` folder @aronasorman, for almost every test :smile_cat:.  We will do more tests today so will re-open if this is indeed an issue.

**Comment by amodia** [comment]
I can't reproduce this issue. I reset the app and delete the `~/.kalite/` folder, the assessments are still loaded when starting the kalite server.

![screen shot 2015-09-29 at 3 18 53 pm](https://cloud.githubusercontent.com/assets/8663934/10157913/c68e0740-66c0-11e5-9bb3-c582900c29ef.png)
