### ISSUE TITLE
Check if assessment.zip was successfully downloaded.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#182]
**Branch** develop

**Target** 0.15.x

**Expected Behavior** Build must fail if the `assessment.zip` is not downloaded successfully.

**Current Behavior** Build continues even if `assessment.zip` did not download.

**Comment by cpauya** [comment]
Re-commenting here (from PR): 

@aron Here's a screenshot of a sample download of `assessment.zip` that's been closed by the remote server... not sure why the remote server did that. :(
![screenshot 2015-09-28 19 32 34](https://cloud.githubusercontent.com/assets/175580/10134389/ff13692e-6617-11e5-885e-d865d862de90.png)

**Comment by aronasorman** [comment]
Rrrrr it's this issue again. Can you check if it happens often for you @cpauya? We've been having this issue lately and we're not sure why exactly. Let's keep an eye on this.

**Comment by aronasorman** [comment]
@jamalex have we disable varnish for assessment.zip?
