### ISSUE TITLE
Can't build windows installer manually.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#185]
**Branch:** `master`
**Expected behaviour:** Must build windows install manually.
**Current behaviour:** Can't build windows installer if the ka-lite has node_modules directory.

**Steps to reproduce:**
 1. Follow the steps on [Instructions to build "KALiteSetup.exe" ](https://github.com/learningequality/ka-lite/wiki/Getting-started)
 2. Compile it with inno setup or run `make.vbs`.

![screen shot 2015-09-29 at 4 44 55 pm](https://cloud.githubusercontent.com/assets/8663934/10160471/614d5c4a-66d0-11e5-8cfa-a9ede9137f90.png)
![screen shot 2015-09-29 at 4 49 11 pm](https://cloud.githubusercontent.com/assets/8663934/10160437/2d2be382-66d0-11e5-8f27-52bf9de8c758.png)

**Workaround**: Delete the node_modules directory inside the ka-lite folder and follow the steps on this link [Instructions to build "KALiteSetup.exe" ](https://github.com/learningequality/ka-lite/wiki/Getting-started)

**Comment by cpauya** [comment]
@amodia What Windows version did you use?

**Comment by amodia** [comment]
I used Windows 7 professional 32 bit.

![screen shot 2015-09-29 at 6 16 40 pm](https://cloud.githubusercontent.com/assets/8663934/10161462/e8f8843e-66d6-11e5-8e79-8eb9feec1d96.png)

**Comment by MCGallaspy** [comment]
Yeah, I've encountered the same thing. Will add a note to the build instructions.
