### ISSUE TITLE
There's a javascript error when  clicking on language tab.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#186]
**Branch:** 0.15.x.

**Windows installer:**   http://field.learningequality.org/KALiteSetup-0.15.0--9-25-15.exe.

**Platform:** IE10 on Win8

**Expected Behavior:** Able to load languages on drop-down `Select language pack`.

**Current Behavior:** There's a javascript error when clicking on language tab.

**Steps to reproduce:**

 1. log in as `Admin`.
 2. click on `Language` tab.

Screenshot:

![screen shot 2015-09-29 at 5 35 16 pm](https://cloud.githubusercontent.com/assets/8664071/10162010/9afe85a4-66da-11e5-838f-aa95cc24e6e5.png)

**Comment by aronasorman** [comment]
I remember @rtibbles and I fixing this exact bug. Perhaps you didn't pull the latest 0.15?

**Comment by rtibbles** [comment]
Indeed, I did. Possible that @MCGallaspy has not had a chance to rebuild the Windows installer yet?

**Comment by MCGallaspy** [comment]
@rtibbles it's possible -- did the fix get merged in after 9/25?

**Comment by MCGallaspy** [comment]
Stale.
