### ISSUE TITLE
Mac installer menu bar icon not set to "processing" while setup is running.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#187]
**Branch:** `master` 

**Expected behaviour:** Menu bar icon must set to "processing" while setup is running.

**Current behaviour:**  Menu bar icon not set to "processing" while setup is running.

**Steps to reproduce:**
 1. Launch the `kalite monitor app`
 2. Click the apply button at the preferences menu.
 3. Notice the menu bar icon is set back to "ready" and not "processing", the "Start KA-Lite" menu is available.
 4. Clicking on the "Start KA-Lite" menu option shows the "KA-Lite is still processing" alert.

**Comment by cpauya** [comment]
Fixed in #196.
