### ISSUE TITLE
Alternatives for writing downloaded assessment items to /tmp

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#191]
Writing assessment.zip to /tmp or other location can cause problems for small devices.

We need this to be configurable with debconf, e.g.:

```
# Set debconf before installing the package
echo "ka-lite-raspberry-pi ka-lite/download-tmp-folder select /other/path" | debconf-set-selections
# (...)
```

Furthermore, we should measure disk space and raise a proper warning or failure if it isn't sufficient, even though wget will also do that. The difference should be that our failure message tells the user who to configure an alternative location for the download or:

> maybe you could check the disk space, and if isn't availabe prints how to download and install it later. It would make the installation smooth.

**Comment by benjaoming** [comment]
Disk space needed: For storing the .zip and for unpacking it.

**Comment by aronasorman** [comment]
We encountered this during SanDIsk development. Would be nice to have a way to specify the temp directory as a general option or setting.

**Comment by benjaoming** [comment]
Working on it right now, it'll check for free disk space in /tmp and the target for unpacking /usr/share/kalite and have a debconf note about the manual method in case disk space is missing.

**Comment by benjaoming** [comment]
Here's what the debconf will say when there's not enough disk space:

![screenshot from 2015-10-13 22 12 31](https://cloud.githubusercontent.com/assets/374612/10466959/86bb8178-71f7-11e5-8705-156f31145cea.png)

**Comment by benjaoming** [comment]
Done
