### ISSUE TITLE
 Possible server crash after cookie expiration

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#194]
Moved from learningequality/ka-lite#4528 

Original post by @EdDixon :

On 0.15 while testing the latest MAC develop release while logged into a fresh installation as admin, I was distracted by a google voice call lasting well over the 30 minutes of expiration time the session cookie allows the admin login. During the call I noticed the browser had become unresponsive and afterwards crashed. Closing the browser I notification flashed that the ka-lite server had started although it was already started and I was logged in earlier. Seems @rtibbles may have a clue what is happening so tagging him and @cpauya on this one? Screenshot one shows the state of the browser before expiration and the second notification of the crash. I did have several other tabs open but the Activity Monitor did not show an overload on the system? 

![2015-09-28_11-15-02](https://cloud.githubusercontent.com/assets/4349806/10151076/2124ae4a-6601-11e5-9f1c-c3f1a8ed0d1e.png)

![2015-09-28_15-26-12](https://cloud.githubusercontent.com/assets/4349806/10151082/2ad13184-6601-11e5-8c00-0f221b6eea38.png)

**Comment by rtibbles** [comment]
This is not an installers issue. It is not a server crash, it is front end javascript related.

**Comment by EdDixon** [comment]
That is good news! The reason I called it a crash is because of the MAC notification from the server that it had (re)started after killing the browser session? Still not sure how that could be a front end issue having received that notification but glad it is resolved, as I have not been able to replicate it since.

**Comment by benjaoming** [comment]
@EdDixon it isn't resolved, Richard just clarified that it was indeed a frontend issue, not a Mac installer issue. So we closed this and reopened the old one :)

**Comment by EdDixon** [comment]
Cool! Thanks for that, the search for it continues then I would really like to replicate it at least once here :)
