### ISSUE TITLE
kalite.bat can't accept user input

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#195]
moved from learningequality/ka-lite#3944

We have a bunch of different kalite.bat logic :) It should probably in the end be part of the Windows installer.

Currently, one is in ka-lite/bin/ and one is generated automatically by setup.py

Original post by @MCGallaspy :

On windows 8, in develop:

Scripts which require user input (like the setup management command without the no-interaction flag) can't accept input when you call them with "kalite.bat manage mycoolscript". Works ok with "python.exe kalite mycoolscript". Since the main commands (start, stop, status) all don't require input, I'm not considering this a release blocker.

**Comment by MCGallaspy** [comment]
I was referring to the file included in the ka-lite repo: https://github.com/learningequality/ka-lite/blob/0.15.x/bin/windows/kalite.bat

I don't know if this is the case with the one generated by setup.py.

**Comment by benjaoming** [comment]
The one generated by setup.py is generated through an example I found on some very thorough blog post some time back, it's worth checking out.

**Comment by MCGallaspy** [comment]
Now using the setup.py generated batch script.

**Comment by benjaoming** [comment]
Cool, quick Q: If we factor out "python-packages" and "dist-packages" logic from setup.py (as I'm planning to do for 0.17), will it have any effect on the windows installer?

**Comment by benjaoming** [comment]
@MCGallaspy

**Comment by MCGallaspy** [comment]
Not sure what you mean exactly, can you elaborate? Basically, the Windows installer generates a "static" sdist using `setup.py sdist --static`, and the installs the kalite package at installation time using the resulting zipfile. So does it affect those steps?

**Comment by benjaoming** [comment]
@MCGallaspy nope, that should be entirely safe! If you don't do anything outside of this regarding these to "data files" locations, then it's totally safe and removing it won't hurt.
