### ISSUE TITLE
Have a ka-lite binary to stop and start the server

### ISSUE THREAD

**Issue by aronasorman** [learningequality/installers#2]
<a href="https://github.com/aronasorman"><img src="https://avatars.githubusercontent.com/u/191955?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aronasorman](https://github.com/aronasorman)**
_Thursday Dec 04, 2014 at 02:33 GMT_
_Originally opened as https://github.com/learningequality/ka-lite/issues/2757_

----

So for Ubuntu we have `service kalite (stop|start)`, but it would be nice to have a standardized command line interface for controlling the server. Hence I propose the `kalite` binary, with the following commands:

`kalite start`
`kalite stop`
`kalite restart`
`kalite gui` (if supported by the platform)

Which should call out the right scripts found in the ka-lite/scripts/ directory. We can then modify the startup scripts to just simply call the right arguments.

**Comment by benjaoming** [comment]
We have just discussed how to separate and encapsulate the kalite application vs. the kalite system service and come up with the following suggestion:

    $ kalite start       <- executable 'kalite' provided by main 'kalite' package
                \
               invokes
                  \
                 $ kalite-service start    <- provided by separate kalite-service-upstart
                    /        \
                 fail       invokes
                  /            \
             $ start.sh      $ service kalite start
          (this is run in        (this command
          case we fail to        is part of the
             find any             package which
          'kalite-service'        supplies
            in the PATH)         os-specific
                                   services)
