### ISSUE TITLE
Some sidebar items are greyed-out after an upgrade on OSX.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#201]
**Branch** 0.15.x

**Target** 0.15.x

**Current Behavior** Users who have installed 0.14 have the `~/.kalite/` folder with assessment items.  Upgrading it to 0.15.x will cause some items in the sidebar to be greyed-out.

**Expected Behavior** After upgrading, the sidebar items must not be greyed-out.

**Alternative Solution** After upgrading, extract the `assessment.zip` manually.

**Steps** After installing, launch the app preferences, go to `Advanced` tab, click on the `Extract Assessment` button, then restart the server.  This will enable those greyed-out items on the sidebar.

This must be mentioned on the docs for now while we figure out a more straight-forward solution that doesn't involve extracting the `assessment.zip` manually.

**Comment by benjaoming** [comment]
I guess the docs update puts us at a state where it's okay to retarget the issue to 0.16? @cpauya

**Comment by aronasorman** [comment]
Yup. Availability stamping is now 'global' (done in a DB instead of a global variable). Should be solved in 0.16. Leaving this open so we can test it.

**Comment by arceduardvincent** [comment]
Hi @aronasorman .
I tested this issue by installing 0.14.2 then upgrade to 0.16.0. However I didn't replicate this issue.
It was solve on #313.
![screen shot 2015-12-21 at 5 57 11 pm](https://cloud.githubusercontent.com/assets/4099119/11928147/554c1d82-a80c-11e5-9cd3-667eb7daa93e.png)

**Comment by cpauya** [comment]
This is already non-extant on the latest `develop` branch.
