### ISSUE TITLE
User warning notification not being cleared properly

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#204]
On MAC (I am told this isn't happening on others) using the latest MAC build for 0.15 develop the user notification after downloading videos continues to appear even after stopping the browser, clearing all browser cookies, or any combination of those and restarting the computer. The user is still told that the server needs to be restarted yet the videos are already listed as available in the video topic tree
![2015-10-02_10-04-53](https://cloud.githubusercontent.com/assets/4349806/10251461/09c384fc-68ee-11e5-9f5a-b68cb58a136e.png)
.

**Comment by aronasorman** [comment]
This is by design. That notification is meant to be persistent.

**Comment by EdDixon** [comment]
Great Job! LOL but @benjaoming is telling me this does not happen on the other platforms and honestly i do feel it is very confusing to the user (it confused me yesterday) because it does look like a notification from KA-Lite that the server needs to be restarted and not just information for the user which could be persistently coded in to the page if that what we want to do?

**Comment by aronasorman** [comment]
Yes, it only happens for the Mac and RPi: https://github.com/learningequality/ka-lite/pull/4510

Things will be better in 0.16, when we have a new cache invalidation mechanism.
