### ISSUE TITLE
0.15 MAC server start fails on El Capitan 

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#214]
After disabling SIP and attempting a reinstall as done in previous tests over the past few days on our latest build, after installation and running the application from the finder/applications folder (unsigned) and completing the preferences dialog  the application starts and appears in the menu bar but choosing the start KA Lite server options never completes and seems stalled with the icon showing the gear icon. Allowed up to 20 minutes for it to get process before giving up on it here.

**Comment by EdDixon** [comment]
also I found no .kalite folder as expected or env variables loaded?

**Comment by cpauya** [comment]
This is related to #208.  A fix has been released for v0.16.x on #284.

**Comment by cpauya** [comment]
We don't officially support El Capitan for releases 0.15.x or below.  The work-around is to disable SIP, see https://github.com/learningequality/installers/issues/208#issuecomment-145639950. 

We can make a hotfix to support El Capitan on previous releases if that's important, @aronasorman any thoughts?

Else, I think we can close this issue?

**Comment by cpauya** [comment]
Closing this as per reasons above.
