### ISSUE TITLE
0.14.2 installer in dungeon server uses wrong KA Lite version.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#215]
**Branch:** 0.14.x

**Expected Behaviour:** Able to download the 0.14.2 installer and use the 0.14.x KA-Lite version.

**Current Behaviour:** Downloading the [0.14.2](http://dungeon.learningequality.org:8085/browse/KL-KALITE014-267) installer in the dungeon server uses the wrong KA-Lite version. 
![screenshot 2015-10-09 17 08 35](https://cloud.githubusercontent.com/assets/4099119/10390645/9c4ff8f0-6eac-11e5-8d0e-048a59fc89df.png)

**Steps to Replicate:**
>1. Download the 0.14.2 in the [dungeon](http://dungeon.learningequality.org:8085/browse/KL-KALITE014-267) server. 
>1. Install the .dmg downloaded to `/Application` folder.
>1. Launch the KA-Lite Monitor from   `/Application` folder.
>1. Open browser and Navigate to `Homepage`.
>1. Scroll down to the `Footer` then notice the KA-Lite version. It uses 0.15.x version.

**Comment by cpauya** [comment]
Is this for the Mac installer only @arceduardvincent?  How about the Windows installer?

**Comment by arceduardvincent** [comment]
Yes it is manifesting on the Mac installer and the Windows installer is not available in the dungeon server yet.

**Comment by arceduardvincent** [comment]
Hi @aronasorman can you review this issue. 
We need to  create a new .dmg so we can test the 0.14.2  KA Lite version.

**Comment by arceduardvincent** [comment]
I built 0.14.2 installer in the `MrPau Team Build`. I found out that the 0.14.2 installer built in this plan used the correct KA Lite version which is 0.14.2 not the 0.15.x.
You may check the artifact on [dungeon](http://dungeon.learningequality.org:8085/browse/KL-OSX-56/artifact) server.
See image as demonstration.
![screen shot 2015-10-14 at 5 14 44 pm](https://cloud.githubusercontent.com/assets/4099119/10479471/20e0f86a-7297-11e5-9b2e-1c5f6b93143e.png)

Using the `setup.sh` and passing arguments on `setup.sh` using the 0.14.2 KA-Lite version has no problem. 
```bash
./setup.sh "https://github.com/learningequality/ka-lite/archive/0.14.x.zip" "http://pantry.learningequality.org/downloads/ka-lite/0.14/content/assessment.zip"

```

It seems the commands issued upon running the build plan maybe the issue.

**Comment by arceduardvincent** [comment]
I think this one should be close.
It is a stale issue.
