### ISSUE TITLE
Option to update the assessment items.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#22]
**Branch** Develop
**Target** 0.14.x
**Expected Behavior**
On the .app preferences dialog, put an option to update assessment items. 

And warn them that the `assessment.zip` is large at 400MB+, and show a download/update progress to be user-friendly.

**Update Steps**

1. Download the `assessment.zip` from https://learningequality.org/downloads/ka-lite/SHORT_VERSION/content/assessment.zip to `$KA_LITE_DIR/data/` folder or any arbitrary location as per user preference.
1. Run `bin/kalite manage unpack_assessment_zip` to unpack it.

**Notes**

1. The build server will generate a `ka-lite` folder which includes the assessment items already.  This folder will be used by the `setup.sh` script to include in the .dmg.
1. The `assessment.zip` is located at https://learningequality.org/downloads/ka-lite/SHORT_VERSION/content/assessment.zip -- example: https://learningequality.org/downloads/ka-lite/0.13/content/assessment.zip

**Comment by MCGallaspy** [comment]
What is we simply include the assessment items with the installer?

**Comment by cpauya** [comment]
Good question @MCGallaspy - I have two reasons for making this an option at the preferences dialog:

1. During `bin/kalite manage setup` - we ask the user re download of the assessment items package as an option, thus my decision to make this an "option-only" for the OS X app.  So if they want, they can visit the preferences dialog and download the assessment items package after the installation.
1. This will allow the users to "force-update" their assessment items if it's already downloaded.

If both cases are false, then we can include the assessment items package when building the installer, not when the user is using it.  Which leaves the question of "How will the users update their assessment items?".

So I think this is our approach: we include the assessment items package when building the installer and provide the option to "update their assessment items" on the preferences dialog.

Your thoughts on this @aronasorman, @jamalex @rtibbles?

**Comment by cpauya** [comment]
As per discussion with @aronasorman - the build server will handle the extraction of the `assessment.zip` into a `ka-lite` folder which the installer will include on the `Resources` folder when the `setup.sh` is ran.

With this, the .app preferences will assume that it already has the assessment items package and will therefore provide the user a way to "update" the assessment items.

**Comment by aronasorman** [comment]
Implemented in latest 0.15.x mac installer.
