### ISSUE TITLE
Add manpage for kalite command

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#223]
:)

@cpauya I accidentally did not include kalite.1.gz in the sdist because I forgot to list it in MANIFEST.in -- so in the Debian, I'll add it manually. There'll be a patch update to fix it.

**Comment by benjaoming** [comment]
![screenshot from 2015-10-14 02 14 55](https://cloud.githubusercontent.com/assets/374612/10471778/741c1380-7219-11e5-9f83-09a92b2fe98b.png)

**Comment by benjaoming** [comment]
it's not pretty but it works :)

**Comment by cpauya** [comment]
Good to know @benjaoming - thanks. :smile_cat:
