### ISSUE TITLE
Run setup during upgrade.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#224]
**Branch** develop

**Target** 0.16.x

**Current Behavior** Setup is not run during an upgrade process.

**Expected Behavior** We should run setup during upgrade as per https://github.com/learningequality/ka-lite/issues/4619

**Alternative Solution** User can click on `Advanced -> Setup` on the Preferences window to run setup after an upgrade.

We must update the docs on this.

**Comment by rtibbles** [comment]
We definitely need to do this, as setup also applies any new database migrations.

**Comment by cpauya** [comment]
Fixed in #278.
