### ISSUE TITLE
Update the LICENCE copyright

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#225]
**Branch:** 0.15.x
**Expected behaviour:** Copyright must updated.
**Current behaviour:** Copyright is not updated.

**Steps to reproduce:**
 1. Download the [KA Lite `OSX installer](https://learningequality.org/r/osx-installer-0-15)
 2. After the download has been completed, double click the .dmg file.
 3. The Copyright is not updated as shown at the screenshot below.
![screen shot 2015-10-14 at 6 55 22 pm](https://cloud.githubusercontent.com/assets/8663934/10481960/e7ee6352-72a6-11e5-919a-d93dbe1dc466.png)

**Comment by cpauya** [comment]
Already fixed in `develop` branch.
