### ISSUE TITLE
Check for user preferences during install or uninstall.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#23]
**Branch** Develop
**Target** 0.14.x
**Expected Behavior**
During install, check for old user preferences and remove them.

During uninstall, if possible, remove the old user preferences.

**Comment by MCGallaspy** [comment]
Updates @cpauya?

**Comment by cpauya** [comment]
Hi @MCGallaspy - sorry this is still outstanding as of today.

The approach here is to modify the [ka-lite-remover.sh](https://github.com/learningequality/installers/blob/develop/osx/ka-lite-remover.sh) - this same script is copied as `KA_Lite_Uninstall.tool` after installation.

Will work on this this week.

**Comment by cpauya** [comment]
Fixed in #357
