### ISSUE TITLE
PPA Install docs for 0.15 need slight changes 

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#230]
The current PPA installation doc does not clearly let the user know that the GUI widget is included with just the PPA installation on both Debian and Ubuntu systems. Also, for a Debian installation after the second step before running "sudo apt-get update", the user will need to manually change the learningequality-ka-lite-jessie.list to replace jessie with trusty within the file itself located at /etc/apt/sources.list.d/

**Comment by benjaoming** [comment]
These issues are solved in

https://github.com/learningequality/ka-lite/pull/5227
https://github.com/learningequality/ka-lite/pull/4794
