### ISSUE TITLE
Ubuntu and Debian GTK GUI locks up 0.15.0

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#231]
After PPA  installing 0.15.0 on current Debian stable both kalite and the kalite-gtk are installed. The dialog box launched the server fine but then stalled with "updating status" and becoming completely non-functional. closing the dialog forced a kill to escape and restarting brought it back to the same state. The server could still be shutdown via the kalite stop command.Screen shots and logs below:

![2015-10-15_21-33-50](https://cloud.githubusercontent.com/assets/4349806/10534195/ff0ef7f4-7391-11e5-9319-abd5e1b8f273.png)

![2015-10-15_18-42-49](https://cloud.githubusercontent.com/assets/4349806/10534200/0f198628-7392-11e5-9996-2fbeba043d21.png)

kaite-gtk.log
```
2015-10-01 04:19:54,566 - kalite_gtk.cli - DEBUG - Running command: [u'/usr/bin/kalite', u'status'], KALITE_HOME=/home/ed/.kalite
2015-10-01 04:26:47,283 - kalite_gtk.cli - DEBUG - Streaming command: [u'/usr/bin/kalite', u'start', u'--port=8008'], KALITE_HOME=/home/ed/.kalite
2015-10-01 04:29:05,958 - kalite_gtk.cli - DEBUG - Running command: [u'/usr/bin/kalite', u'status'], KALITE_HOME=/home/ed/.kalite
2015-10-01 04:35:40,294 - kalite_gtk.cli - DEBUG - Running command: [u'/usr/bin/kalite', u'status'], KALITE_HOME=/home/ed/.kalite
2015-10-01 07:26:06,308 - kalite_gtk.cli - DEBUG - Running command: [u'/usr/bin/kalite', u'status'], KALITE_HOME=/home/ed/.kalite
```
server.log
```
[01/Oct/2015:04:29:05] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[01/Oct/2015:04:29:05] ENGINE Listening for SIGHUP.
[01/Oct/2015:04:29:05] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[01/Oct/2015:04:29:05] ENGINE Listening for SIGTERM.
[01/Oct/2015:04:29:05] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[01/Oct/2015:04:29:05] ENGINE Listening for SIGUSR1.
[01/Oct/2015:04:29:05] ENGINE Bus STARTING
INFO:cherrypy.error:[01/Oct/2015:04:29:05] ENGINE Bus STARTING
[01/Oct/2015:04:29:05]  Loading and serving the Django application
INFO:cherrypy.error:[01/Oct/2015:04:29:05]  Loading and serving the Django application
[01/Oct/2015:04:29:05] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO:cherrypy.error:[01/Oct/2015:04:29:05] ENGINE Started monitor thread '_TimeoutMonitor'.
[01/Oct/2015:04:29:05] ENGINE Serving on 0.0.0.0:8008
INFO:cherrypy.error:[01/Oct/2015:04:29:05] ENGINE Serving on 0.0.0.0:8008
[01/Oct/2015:04:29:05] ENGINE Bus STARTED
INFO:cherrypy.error:[01/Oct/2015:04:29:05] ENGINE Bus STARTED
```

**Comment by EdDixon** [comment]
Same type lockup occurs on the Ubuntu versions as well both 14 LTS and 15.x I repeated the tests and replicated the problem with an additional 1GB of RAM. AT one point it locked up so bad a reset was the only escape! Changing title to include Ubuntu as well... 

![2015-10-16_11-55-09](https://cloud.githubusercontent.com/assets/4349806/10549734/1b16244a-7400-11e5-9ffb-b23eb2fb1b1a.png)

**Comment by EdDixon** [comment]
Please note: The kalite command is unaffected and  everything works as expected when the GTK dialog is not used.

**Comment by EdDixon** [comment]
There also seems to be a lot of confusion about the fact that the kalite-gtk is installed, while installing the  with the standard bundle through PPA which the current documentation does not seem to indicate. The user will assume a separate install is required for it when following our documentation and I m not sure myself that it is not expected to be a separate step and the build haven both is somehow broken at this point. 

![morethanexpected](https://cloud.githubusercontent.com/assets/4349806/10562578/d3476f9a-751f-11e5-96fa-0d34fbadda0e.png)

**Comment by EdDixon** [comment]
@benjaoming  I have been thinking a lot about the ka-lite-gtk problems I have been having when doing a PPA install and think I may have a clue to what could be happening. The PPA is pulling from the repo directly and not pulling it in from the leq site. So when we do a PPA install (we are not getting the exact same package to begin with) as documented and we could be getting 0.16 develop if its 0.15.1 label hasn't been changed yet. If changes there have been made to merge these two packages that would explain it.

**Comment by EdDixon** [comment]
Checking the installed version from the PPA install as documented I am showing 14.2 which leaves no doubt in my mind it is related to the repo the commands are pulling from here: So not 0.16 develop anyway but should be easy enough to fix?

![2015-10-18_6-37-05](https://cloud.githubusercontent.com/assets/4349806/10564086/132098e2-7563-11e5-949f-e6ed4ec0c713.png)

**Comment by benjaoming** [comment]
You can install the latest KA Lite from PyPi or from the uploaded deb.

The PPA is not updated for 0.15 yet.

**Comment by EdDixon** [comment]
Thanks @MCGallaspy we need to remove that from the documentation or wait for @benjaoming to resolve the repo issue there. Will leave this open until it is resolved one way or the other. @benjaoming Thanks,

**Comment by benjaoming** [comment]
Hi @EdDixon - hope you're good man, it's been way too long!!

This issue was most likely caused because the `kalite start` subcommand or `status` command was taking time to respond. Newer versions of ka-lite-gtk does not lock up but uses a background thread to monitor the results :)
