### ISSUE TITLE
Preferences dialog must be always on top.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#236]
**Branch develop:** `develop` (os x installer)
**Expected behaviour:** preferences dialog must be always on top.
**Current behaviour:** preferences dialog will move back if you click another window.

**Steps to reproduce:**
 1. Navigate to `ka-lite monitor` preferences window.
 2. Click another window at the back of the  `ka-lite monitor` preferences window.
 3. The `ka-lite monitor` preferences window will move back.

**Comment by cpauya** [comment]
Closed in #237
