### ISSUE TITLE
Remove creation of admin account during setup.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#238]
**Branch:** `develop` (os x installer)
**Expected behaviour:** Remove creation of admin account during setup.

This is causing a bug wherein it will auto-create an admin user every time the Apply button is clicked.
So if you specify a for the first attempt, then for the second attempt, that will yield two admin accounts.
Let's also remove specifying the admin account during the setup command when the Apply button is clicked. This way we don't have to create an admin account every time setup is run.

Related to:  https://trello.com/c/f1XwaiuM/27-remove-setup-mgmt-command-from-installer

**Comment by cpauya** [comment]
Fixed in #277.
