### ISSUE TITLE
Include pyrun in Resources folder for the Xcode project.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#246]
**Branch:**  `Develop`

**Expected Behavior:** `Pyrun` will be included in `Resources` folder for the `Xcode` app.  
 
**Current Behavior:** When we clone it from `Installers` repository, then open the app in `Xcode` it require a `pyrun` in order to build it from `Xcode`.  

**Steps to reproduce:** 

1. Clone from `Installers` repository
2. Double click `KA-Lite.xcodeproj` from `/installers/osx/ka-lite`. to open it from `Xcode`.
3. Try to build the app in `Xcode`. There's an error like in the screenshot below.

**Screenshot(s):**
![xcodeerror](https://cloud.githubusercontent.com/assets/8664071/10839486/68532414-7f0f-11e5-9c5c-6a174d286dfc.png)

**Comment by cpauya** [comment]
Fixed in #257.
