### ISSUE TITLE
Removing video content should also provide progress bars

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#251]
While removing videos from an installation (for a language change for example) it is very time consuming and there are no progress bars to let the user know the process is still underway.

**Comment by cpauya** [comment]
Hi @EdDixon - I haven't tried to use multi-language checks (especially videos too) for an install yet so this is interesting.  Some questions for you:

1. Did you remove the videos inside the ka-lite web app, using one of the installers, or manually in a file system of the OS?
2. Which OS did you use for this?

If in case you used the ka-lite web app for this, maybe we should file this on the ka-lite repo?

**Comment by benjaoming** [comment]
I think we can remove this issue, as it relates to the source package. The use case is also rather narrow, but in a broader sense, we need a "cleanup" command that can delete unused videos which will eventually occur if you upgrade from one KA Lite to another or if you just wanna copy in the videos that were downloaded last year.

But as KA Lite is going into "legacy mode", it's unlikely this can be done.
