### ISSUE TITLE
Put KA-Lite version at the right side of KA-Lite logo.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#255]
**Branch:** `Develop`

**Expected Behavior:** Must have a version in `KA-Lite Preferences` dialog.

**Current Behavior:** No `KA-Lite` version in `KA-Lite Preferences` dialog.

**Steps to reproduce:**

1. Launch `KA-Lite` app from the `Applications` folder.
2. Click `Preferences...` in menu bar.
3. A `KA-Lite Preferences` dialog will appear. 
![screen shot 2015-11-05 at 1 53 21 pm](https://cloud.githubusercontent.com/assets/8664071/10961145/84b92106-83c6-11e5-8ed0-cb699cafca76.png)

Notice that the `KA-Lite Preferences` dialog don't have a version.

**Comment by cpauya** [comment]
Fixed in #261
