### ISSUE TITLE
OS X Installer changes

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#264]
**Branch**  `Develop`

**Target** `feature/osx-0.16.x`

**Current Behavior**
During the first run, the .app copy `bin/kalite` executable to `/usr/bin/kalite` which will ask the password. 

**Expected Behavior**
The installer should prepare the`kalite` executable and environment variables not the .app. 
During the first run, the user should not be prompted anymore for the password because we already ask the password in the installation process.

**Checklist**
- [x] copy `pyrun-2.7` (after running `pyrun setup.py sdist --static`) to `/Users/Shared/`?
- [x] symlink `/Users/Shared/pyrun-2.7/bin/kalite` executable to `/usr/bin/kalite` or `/usr/local/bin/kalite`
- [x] set the environment variable : `KALITE_PYTHON` to the location of `/Users/Shared/pyrun-2.7/bin/pyrun`
- [x] run `shebangcheck.py /Users/Shared/pyrun-2.7/bin/pyrun`
- [x] create the `/Library/LaunchAgents/org.learningequality.kalite.plist`

**Later Checklist**
- [x] run `pyrun manage.py setup` (if there's no empty database found)
- [x] extract the `assessment.zip`
- [ ] upgrade path?

**Comment by cpauya** [comment]
@arceduardvincent Do you have updates on this issue?  Can you change the text accordingly?

**Comment by arceduardvincent** [comment]
Yes, I will update the upgrade path checklist when this #283 is merge then we can declare this issue is done.

**Comment by cpauya** [comment]
We will work on the upgrade path in another issue.  The rest are fixed in #278.
