### ISSUE TITLE
Add README.md and assessment.zip into .gitignore.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#265]
**Branch:** `Develop`

**Expected Behavior:** Ignore `/pyrun/README.md` and `/pyrun/assessment.zip`.

**Current Behavior:** `/pyrun/README.md` and `/pyrun/assessment.zip` are not ignored.

**Steps to reproduce:**  

1. Clone from `Installers` repository. 
2. Checkout `develop` branch.
3. Run `setup.sh` in `osx` directory. 
4. After `setup.sh` is done, run `git status` in the terminal.
5. Observed that the README.md was deleted and assessment.zip was added.

**Comment by cpauya** [comment]
We're no longer including the `pyrun` and `assessment.zip` in the .app itself, see #266.

Won't fix this.
