### ISSUE TITLE
OS X Application changes

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#266]
**Branch:** `develop` (os x installers) 

Since we are offloading some functionalities to the installer, the .app must be changed for such.

REF: [OS X Installer changes](https://trello.com/c/YrrNklzn/85-os-x-installer-changes)

Since we allow the customization of paths for KA-Lite (database, contents, etc), the .app must also be updated to set the environment variables.

- [x] remove pyrun-2.7
- [x] remove assessment.zip
- [x] remove copying the bin/kalite executable
- [x] remove reset app
- [x] remove the shebangcheck.py
- [x] remove the setup of environment variables like KALITE_PYTHON, etc
- [x] remove making the `/Library/LaunchAgents/org.learningequality.kalite.plist`

**Comment by cpauya** [comment]
Fixed in #268.
