### ISSUE TITLE
Make a "reset.sh" script.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#269]
**Branch:** `Feature` (osx-0.16.x os x installers)

This is the equivalent of the "Reset App" button of the .app.

- [x] delete the symlinked /usr/bin/kalite or /usr/local/bin/kalite
- [x] delete the /Library/LaunchAgents/org.learningequality.kalite.plist
- [x] Remove the KALITE_PYTHON env var

**Comment by cpauya** [comment]
Fixed in #270.
