### ISSUE TITLE
Use kalite executable when running commands in NSTASK class.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#273]
**Branch:** `feature/osx-o.16.x` (osx installer)

**Current Behaviour:** NSTASK class used `pyrun` when running ka-lite commands.

**Expected Behaviour:** NSTASK class must use `kalite` executable when running ka-lite commands.

REF: https://github.com/learningequality/installers/pull/268#discussion-diff-44636929

**Comment by cpauya** [comment]
Fixed in #274.
