### ISSUE TITLE
debconf input prompted twice or more in 0.15.0-ubuntu3

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#275]
Currently, installing with `dpkg -i` and `apt-get install` is behaving differently:

On Debian Jessie, I am asked once with `dpkg -i file.deb` but twice with `apt-get install ka-lite`.

@EdDixon reports to be asked several times even when using `dpkg -i`.

**Comment by radinamatic** [comment]
Ubuntu 15.04, got asked twice while installing with `dpkg -i file.deb`. Will retest with `apt-get install` and get back.

**Comment by benjaoming** [comment]
@radinamatic yup, it's already confirmed :)

**Comment by EdDixon** [comment]
The expereince is different between the PPA questions and the dpkg
questions but both are basiclly asking which account to use multiple times
in the case of dpkg just twice? Not sure why wehaven't made an issue for
this in installers but if we should just let me know?

Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE, Support FLE via Amazon Smile!
<https://learningequality.org/donate/>
M (575)-201-3691

**Comment by benjaoming** [comment]
> Not sure why wehaven't made an issue for this in installers but if we should just let me know? 

This *is* the issue? :)

**Comment by EdDixon** [comment]
LOL indeed, I was replying in the email thread without realizing where they were coming from, good to know! In the case of a dpkg -i install it is not a huge problem provided the installer uses the same account both times. I am not sure of what the consequences could be of using  a different account when asked the second time (during the test here stuck with the defaults) but, in the case of the PPA it asks a total of 3 times the same question with an input box defaulting to the current user's name. Attaching a traceback done recently wth the debug option to a dpkg install and screen shot of the repeating question.
