### ISSUE TITLE
Implement auto start on login.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#288]
**Branch:** `develop` (os x installers)

**Expected behavior:** `KA Lite` application must  auto start if the user check the "Auto start on login" checkbox in KA Lite preferences dialog.

**Comment by djallado** [comment]
@amodia I tested your PR and the auto login works in my local, but when I click `Start KA Lite` in menu option, I got an error in `KA-Lite Preferences Logs. 
Here's the screenshot:
![screen shot 2015-12-03 at 11 24 26 pm](https://cloud.githubusercontent.com/assets/8664071/11564860/60303232-9a16-11e5-9086-e9479f82dab1.png)

But when I quit the app and `Start KA Lite` again then it works properly.

**Comment by cpauya** [comment]
@djallado Can you confirm this is fixed in #293 already?  I think we can close this now.

**Comment by djallado** [comment]
@cpauya I tested it again with the latest changes of @amodia PR and it was solved already. I can't replicate the one I comment above again.

**Comment by cpauya** [comment]
Thanks.  Fixed in #293.
