### ISSUE TITLE
Windows upgrade from 0.15.0 to 0.15.1 removes account data

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#297]
While testing the 0.15.1 installer and upgrade process from 0.15.0 I encountered on metal and replicated in VM that all accounts are lost including the admin account during an upgrade from a previous 0.15.0 install. This occurred on Windows 10 and has only been replicated in that environment so far. I have not looked at the contents of the remaining SQLite file to see if just the accounts are removed or all data in the database file, but it does appear from the available UI that all data is has been removed.

1)To replicate Install KA-Lite 0.15.0
2)Create Admin, coach, and user accounts
3) do some exercises to populate the student account
4) run the current 0.15.1 installer to do the upgrade
5) during that prior step there is a dialog showing the uninstallation of the previous 0.15.0 install at the very next dialog with options for the startup configuration you can navigate to the .kalite/database folder and verify that the database file is still there 
6) proceed with completion of the upgrade
7) you will discover the admin account has to be created again so go ahead and do that (with exactly the same credentials if you want)
8) you will also find the device needs to be registered again go ahead and do that using the same method as previous as well if desired(in my case I was using one click registration methods)
9) Go to the manage default facility tab and you will see the accounts you created are no longer there either. 

It may be that the student data does still exist in the database file and the relational association's are now broke, at this point I do not know. I am trying to examine the database itself now to see if those records still exist.

**Comment by MCGallaspy** [comment]
Confirmed, let me try to figure out the cause.

**Comment by MCGallaspy** [comment]
Found the issue: https://github.com/learningequality/installers/blob/0.15.x/windows/installer-source/KaliteSetupScript.iss#L417

Data gets trampled under some circumstances. Solution is to only copy database file if one doesn't exist. Will submit patch for 0.15.x branch of installers, then release a fixed 0.15.1 installer. However on `develop` in the ka-lite repo, this is made redundant by https://github.com/learningequality/ka-lite/pull/4656. So on installers `develop` I'll simply remove this functionality.
