### ISSUE TITLE
Help text for the custom data path control.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#301]
**Branch:** `develop` (os x installers)
**Expected behavior:** Create help text for KA Lite custom data path control at KA Lite preferences dialog.

**Comment by cpauya** [comment]
@amodia Let's fix the alignment and text issues then we can close this.

![6b730ee6-9d0c-11e5-99c8-3bdc03bd92fd](https://cloud.githubusercontent.com/assets/175580/11646505/b16c91e6-9d99-11e5-8aef-ccc67cf50299.png)

**Comment by cpauya** [comment]
Fixed in #311
