### ISSUE TITLE
Respect previous debconf during upgrade

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#304]
@EdDixon 
> Is there anyway that if it sees a previous install it can skip that step for the installer to prevent them from creating a new account and fool them into thinking they have lost the data

There should be a way to avoid setting new default values when upgrading and instead retain previous values.

This possibly also affects users having predefined debconf for unattended installation.

**Comment by MCGallaspy** [comment]
@benjaoming agree or disagree about the "release blocker" status?

**Comment by benjaoming** [comment]
I think it's still a release blocker, shouldn't be too tough to solve.

**Comment by benjaoming** [comment]
Will be fixed in #367
