### ISSUE TITLE
Nginx setting for user home's .kalite folder is not set

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#305]
If not using ka-lite user, kalite will run with /home/user/.kalite and this needs to be defined in /etc/ka-lite/nginx.d/blah.conf

The consequence is that static files, videos etc. won't show.

**Comment by MCGallaspy** [comment]
You mean, if the user runs ka-lite as a *different* user than the one specified at install time (using the deb file)? For instance, if I install on the RPi and choose `pi` as the user at that time, do I need to do anything special? Or should I have specified a *different* user still to be the ka-lite useR?

**Comment by benjaoming** [comment]
It's related to what the user puts during the installation when prompted by debconf:

![username](https://cloud.githubusercontent.com/assets/374612/11600071/b371c334-9aca-11e5-9cb1-f09c0e82c997.png)

**Comment by MCGallaspy** [comment]
So you're saying it's an issue when I run as a different user than what I specified in that command prompt?

**Comment by benjaoming** [comment]
Yes, if you don't put `ka-lite` as the username, it will fail to serve static media.

If you want it to work for a different user, you need to put something in `/etc/ka-lite/nginx.d/myprecious.conf` - like so:

    set $kalite_home /home/myuser/.kalite;

This line is included in the nginx config in `/etc/nginx/sites-available/kalite.conf`.

**Comment by benjaoming** [comment]
c4ec18d

**Comment by benjaoming** [comment]
Fixed in #295, verified that it works

**Comment by benjaoming** [comment]
Also, the 0.15.1-ubuntu2 with the fix is in https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+packages
