### ISSUE TITLE
Downloaded 0 of 1 videos successfully.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#307]
**Branch:** `Develop`

**Expected Behavior:** Give exact success message after a video download.

**Current Behavior:** There's a message "Downloaded 0 of 1 videos successfully." after a video download.

**Steps to reproduce:**

Using El Capitan in VM

 1. Install `KA-Lite.pkg`.
 2. Launch `KA-Lite.app` from the `Applications` folder.
 3. Click on `Start KA Lite` from menu option.
 4. Click `Open in Browser` from menu option when ready.
 5. Login as admin.
 6. Click on `Video` tab.
 7. Select a video you want to download in a video tree.
 8. Click on `Please select videos to download (below)` button.
![screen shot el capitan](https://cloud.githubusercontent.com/assets/8664071/11624830/73e1e070-9d11-11e5-9606-1a62e5b4208f.png)

The same as when I use `Yosemite` in VM.
![screen shot yosemite](https://cloud.githubusercontent.com/assets/8664071/11624916/0d053d56-9d12-11e5-8491-2a818cf0d8d2.png)

Note: If downloading a video will take a long time the message above is given, otherwise it works properly.

But when I use Actual machine using `Yosemite`, video downloads will work properly even if I tried many times.  

![screen shot many times](https://cloud.githubusercontent.com/assets/8664071/11625285/ba9ef2fc-9d14-11e5-98c5-c142de32b193.png)

**Comment by cpauya** [comment]
I'm not sure if this happens only under VirtualBox.  @djallado Can you also using the `ka-lite` repo later?  Maybe we need to file this there instead of here.

**Comment by djallado** [comment]
@cpauya & @aronasorman, I tested this using El Capitan in actual machine, video download is working.
![screen shot el cap final](https://cloud.githubusercontent.com/assets/8664071/11630684/7c4732ec-9d39-11e5-803b-5f067f011c4c.png)

**Comment by cpauya** [comment]
Maybe it's the network setting of your VM?  Are you using Bridged-mode?

**Comment by djallado** [comment]
@cpauya I tested it using NAT-mode in my VM and video download is working.

**Here's the screenshots:**

![screen shot 2015-12-08 at 11 28 38 am](https://cloud.githubusercontent.com/assets/8664071/11647553/3d7d53d2-9da4-11e5-98cb-36b9aa20f211.png)
This is my network setting.

![screen shot 2015-12-08 at 11 03 04 am](https://cloud.githubusercontent.com/assets/8664071/11647557/4d1286aa-9da4-11e5-9a38-9c7dd151b9b8.png)
In my first download I selected 1 video.

![screen shot 2015-12-08 at 11 07 44 am](https://cloud.githubusercontent.com/assets/8664071/11647567/65a4d448-9da4-11e5-84c6-76cc41b8f91e.png)
In my second download I selected 3 videos.

So maybe we could close this issue.

**Comment by cpauya** [comment]
Hey this is good @djallado!  Can you close this issue now?

**Comment by djallado** [comment]
The resolution for using the `El Capitan` on VM (Virtual Machine) is to set the network to `NAT` like in the screenshot above.
