### ISSUE TITLE
Topic tree items are greyed-out during first install.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#308]
**Branch:** `Develop`

**Expected Behavior:** Assessment items will work after the installation.

**Current Behavior:** `Learn` tab is greyed during first install.

**Steps to reproduce:**

 1. Install `KA-Lite.pkg`.
 2. Launch `KA-Lite.app` from the `Applications` folder.
 3. Click on `Start KA Lite` from menu option.
 4. Click `Open in Browser` from menu option when ready.
 5. Click on `Learn` tab.
![screen shot assessment1](https://cloud.githubusercontent.com/assets/8664071/11627317/79870f10-9d24-11e5-85d6-ea5e3ec6670f.png)
Observe that the topic tree is greyed.

Reinstall `KA-Lite.pkg` again and proceed to step 2 thru 5:
![screen shot assessment2](https://cloud.githubusercontent.com/assets/8664071/11627471/7804e850-9d25-11e5-96b4-1a006ec8f08e.png)
Observed that the Assessment items are working properly.

**Comment by cpauya** [comment]
@djallado Maybe we should title this "Topic tree items are greyed-out during first install?"

**Comment by cpauya** [comment]
Probably related to #201.

**Comment by amodia** [comment]
@djallado I think the solution here is on the `post_installation script` we need to run first the `kalite manage unpack_assessment_zip` and run `kalite manage init_content_items --overwrite & kalite manage setup --noinput`. this worked on the KA Lite application.

**Comment by cpauya** [comment]
Assigning this to @arceduardvincent because this looks like an installer task.

**Comment by cpauya** [comment]
Fixed in #313.
