### ISSUE TITLE
Make "sudo kalite" switch to default user

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#314]
Being a platform specific thing, I would suggest that we create a top-level "kalite" command that automatically switches to the user defined in `/etc/ka-lite/username`.

Scenario of a deployment where root account is in use:

> Every time kalite stops and have to start again the command sudo su ka-lite ... to run the command as its printed was not working, switching to root was simpler to execute, specially because of who will be maintaining once its on the field.

**Comment by aronasorman** [comment]
Understood. Commencing judgement day.

**Comment by benjaoming** [comment]
Seems this barcode scanner works then :D

**Comment by MCGallaspy** [comment]
I think this is fixed? Can I close @benjaoming?

**Comment by benjaoming** [comment]
No actually not. But ka-lite does warn the user if they are not running `kalite` as the user specified in `/etc/ka-lite/username`. However, this issue was to make it automatically switch to that user if it's invoked with `sudo`.

**Comment by benjaoming** [comment]
Introducing a new proxy `kalite` command seems at this point of eternal "feature freeze" unlikely to happen.

As an alternative, I would like to implement a policy within the upstream `kalitectl.py` to never allow it to run as admin user, but I'm aware of a certain implementations that does this, so I vouch we don't do that.

Instead, I think we should accept that `bin/kalite` as it is will complain if you run it as a non-default user as described earlier.
