### ISSUE TITLE
Make a release_notes file for mac.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#316]
Make a release notes for mac installer.

References:
 *  https://en.wikipedia.org/wiki/Release_notes
 *  http://stackoverflow.com/questions/638423/how-should-release-notes-be-written
 *  https://github.com/django/django/tree/master/docs/releases

Example:
 * [Transmission BT Release Notes](http://www.transmissionbt.com/)

**Comment by cpauya** [comment]
Fixed in #325.
