### ISSUE TITLE
Apply button must disable if no changes in the preferences dialog.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#317]
**Branch:** `develop` (OS X installers)
**Current behavior:** Apply button is always enabled.
**Expected behavior:** Apply button must disable if no changes in the KA Lite preferences dialog.

**Steps to reproduce:**
1. Launch the KA Lite OS X application.
2. On the menu bar KA Lite icon, select Preferences.
3. Observe that the Apply button is always enabled.

**Comment by cpauya** [comment]
Fixed in #318
