### ISSUE TITLE
Error reading secret key file [Errno 21]

### ISSUE THREAD

**Issue by radinamatic** [learningequality/installers#320]
Error reading secret key file [Errno 21]

**Branch**: 0.16 installer (build # 81) on Windows 7 & 8

**Current Behavior**:  

These error messages appear during the installation, which, however apparently manages to finish:

Windows 7

![secret_key](https://cloud.githubusercontent.com/assets/1457929/11842191/4ddbe216-a402-11e5-878b-d6139ac3fcd6.png)

Windows 8.1

![ie11 - win8 1 pre python 3 5 running - oracle vm virtualbox_102](https://cloud.githubusercontent.com/assets/1457929/11883436/364198a0-a513-11e5-9003-466959ba6b8a.png)

**Comment by MCGallaspy** [comment]
The secretkey stuff isn't really an error -- just unfortunately worded output. Will change that. However, the dialog boxes that now appear are seemingly a legitimate error.

**Comment by radinamatic** [comment]
Ok, I'll change the title of the issue.

**Comment by radinamatic** [comment]
Or better, open a separate one for those.
