### ISSUE TITLE
KA Lite application must not load if `kalite` executable is not found.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#327]
**Branch:** `develop` (OS x installer)
**Current behavior:** KA Lite application will load even if `kalite` executable is not found.
**Expected behavior:** KA Lite application must not load if `kalite` executable is not found.

**Steps to reproduce:**
 1. Install the OS x KA Lite application.
 2. Remove the kalite executable at `/usr/local/bin/kalite`
 3. Launch the KA Lite application.

**Checklist:**
 
- [x] Notify user that kalite executable is not found
- [x] Log the error message for reference
- [x] Don't load the application

**Comment by cpauya** [comment]
Fixed in #328.
