### ISSUE TITLE
"Running package scripts" lacks description of what's happening

### ISSUE THREAD

**Issue by aronasorman** [learningequality/installers#331]
My installation process spent about 5 minutes in this step: 
![screen shot 2016-01-05 at 08 10 26](https://cloud.githubusercontent.com/assets/191955/12117132/2a368870-b384-11e5-9f5c-cb22db557bbd.png)

It would be nice if there were some more description of what exact step is happening. Or is this just the `setup` command?

**Comment by aronasorman** [comment]
Also, why is a restart needed?

**Comment by cpauya** [comment]
Yes @aronasorman, I agree it'll be good to show the steps being run, it's quite a long wait.  Here's what actually happens here:

1. run the pre-installation script (runs the `ka-lite-remover.sh` script);
2. copying the payloads to the `/Users/Shared/ka-lite/` (pyrun, assessment items, scripts);
3. run post installation script (create the .plist, shebangcheck, syncdb, init_content_items, unpack_assessment_zip, setup, copying the uninstall script).

We will check if it's possible to show what's happening in the Installation dialog within the Packages module - though I wouldn't count my hopes high. :smile_cat: 

The restart is to make sure the following, specially in the context of an upgrade from older versions:

1. that the `KALITE_PYTHON` environment variable is set properly, using the .plist - we are now using the one in `/Users/Shared/ka-lite/pyrun-2.7/` whereas the previous version uses the one in the `KA-Lite-Monitor.app/Contents/Resources/pyrun-2.7/` folder;
2. that the `KA-Lite.app` is used (there's a possibility that the .app from previous version is still loaded during the upgrade process)

We will do more testing on this specially on the upgrade process.

**Comment by arceduardvincent** [comment]
Hi @aronasorman and @cpauya .
I was not able to find any alternative how to put some description in the `Installation` step.
As you can see the [Customizing a distribution interface ](http://s.sudre.free.fr/Software/documentation/Packages/en/Distribution_UI_Customization.html) in packages didn't support displaying the installation process description. 

The `Installation` step work's on this manner: displays a message that informs the user about the result of the installation. The message is only displayed if the installation is successful or a failed installation.

**Comment by cpauya** [comment]
Hi @aronasorman - we cannot find a way to display the steps of the installation (or customise it) during the "Running package scripts..." step.

The command that takes a long time is inside the `post_installation.sh` script, specifically: `kalite manage init_content_items --overwrite`.  It takes about a minute or two to finish then the installer proceeds to the `kalite manage unpack_assessment_zip` step.

As an alternative, the user can open the Console application and search for "ka-lite" to see the details of the installation, see screenshot:
![screenshot 2016-01-28 18 57 47](https://cloud.githubusercontent.com/assets/175580/12642624/fc6e4d8a-c5f1-11e5-8c13-af822896f017.png)

The good news is that a restart is not required after installation. :smile_cat: 

I used this OS X installer at Bamboo http://dungeon.learningequality.org:8085/browse/KL-MT16-59/artifact for my tests.

I think we can close this issue already.

**Comment by aronasorman** [comment]
Note: the current iteration of 0.16.x will not require `init_content_items` anymore, as it has been generated beforehand. So this may be a non-issue in the future. Feel free to close if you want.
