### ISSUE TITLE
Facilities, Videos, Languages tabs aren't showing during the upgrade.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#337]
**Branch:** Develop (OS X installer)
**Current behavior:** Facilities, Videos, Languages tabs  aren't showing if 0.15.1 KA Lite OS X installation is upgraded to 0.16.
**Expected behavior:** Facilities, Videos, Languages tabs must show.

**Steps to reproduce:**

 1. Download the [0.15.1 KA Lite OS X installer release](http://pantry.learningequality.org/downloads/ka-lite/0.15/installers/mac/KA-Lite-0.15.1.dmg).
 2. Install it on your machine.
 3. Start the KA Lite server and navigate to `MANAGE` tab and observe that the Facilities, Videos, Languages tabs are visible.
 4. Download the [0.16 KA Lite OS X installer release](http://dungeon.learningequality.org:8085/browse/KL-MT16-47/artifact/shared/KA-Lite-0.16-OSX-Installer/KA-Lite.pkg) and install it to upgrade the 0.15.1 KA Lite OS X installation on your machine.
 5.  Start the KA Lite server and navigate to `MANAGE` tab and observe that the Facilities, Videos, Languages tabs are not visible.

I attached a screenshot below.

![screen shot 2016-01-08 at 2 59 50 pm](https://cloud.githubusercontent.com/assets/8663934/12193725/8a89219e-b625-11e5-866a-876d98d63539.png)

**Comment by aronasorman** [comment]
Rerun `make assets`.

**Comment by arceduardvincent** [comment]
Hi @aronasorman .
We can't rerun the `make assets` during upgrading 0.15.x  to 0.16.x when it is on the client machine.
The client machine may not have a `developer tools` to run the `make assets`.

The behavior above manifested when I upgrade 0.15.x to 0.16.x in my virtualbox.
![screen shot 2015-12-22 at 3 49 31 pm](https://cloud.githubusercontent.com/assets/4099119/12253920/87ec04a0-b91e-11e5-840b-833a68d4b5ca.png)

**Comment by aronasorman** [comment]
@arceduardvincent `make assets` should be done during the installer build process, and the new assets just copied to the right directory.

**Comment by arceduardvincent** [comment]
We have already issued the "make dist" on the [build.sh](https://github.com/learningequality/installers/blob/develop/osx/build.sh#L258) .

Should we rerun the `make dist` again?
I found out some invalid solution on how we deal with that issue, when we remove the ". kalite" 
the `Facilities`, `Videos`, `Languages` tab` are showing so I was suspecting that we have a problem with upgrading the static files on the newer one?.

**Comment by aronasorman** [comment]
If the new installer has the assets built by make assets, then replacing the current assets should do the trick. No need to run `make assets` in the client.

**Comment by cpauya** [comment]
Fixed in #342.
