### ISSUE TITLE
Tooltip help isn't too user friendly

### ISSUE THREAD

**Issue by aronasorman** [learningequality/installers#338]
I'm referring to this:

![screen shot 2016-01-08 at 08 44 28](https://cloud.githubusercontent.com/assets/191955/12203498/27f70aaa-b5e4-11e5-8d58-fd22b8313027.png)

My expectation is that if I click that button a help window would pop up. Instead nothing is happening, and the only way I even knew that the tooltip containing help text would appear was that someone informed me. Else, I'd think this button isn't working.

Strongly suggest to have a pop up window instead.

**Comment by amodia** [comment]
@aronasorman I'm working on this issue. This is my working branch https://github.com/mrpau/installers/tree/feature/338-tooltip-help-isnt-too-user-friendly

**Comment by cpauya** [comment]
@aronasorman Can we show an alert dialog when the "?" button is clicked for now?  I think making the help window will take a few days and we'd like to do more upgrade testing.

Or perhaps @amodia can show another dialog if the alert dialog does not allow custom text formatting.

**Comment by aronasorman** [comment]
@cpauya Sounds like a good temporary solution.

**Comment by cpauya** [comment]
Hi @aronasorman - this is fixed in #343 - perhaps we can close this already?

**Comment by radinamatic** [comment]
I know this is after the fact, but let's keep in mind that from the accessibility point of view, pressing the actual button (to access some additional content like help) is almost always preferred to tooltip-from-hover solution. I don't have first hand experience how/if VoiceOver screenreader reads this on Mac (hopefully that will change very soon), but that's true for browser development.

**Comment by cpauya** [comment]
Thanks for that @radinamatic - And yes we no longer have the tooltip, we used a Popover when the "?" button is clicked.  #343 shows more details (and the link to the Apple OS X Human Interface Guidelines on Popover) including a screenshot of the Popover. :smile_cat:

**Comment by radinamatic** [comment]
Thanks @cpauya, one of the pain points is the closing of "alternative" content views. Wheather the Close button is solution or not is still [being discussed often](http://ux.stackexchange.com/questions/68377/can-we-expect-users-to-close-popovers-by-just-clicking-away), so when implementing popovers without explicit Close button, make sure that they can at least be closed by ESC key, and not by just clicking away with mouse.
