### ISSUE TITLE
A restart is required after installation.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#340]
**Branch:** Develop (OS X installer)
**Current behavior:** After a successful installation the installer wizard prompt you to restart.
After successful installation, the `KALITE_PYTHON` environment variable is running on the sudo context. We need to restart the machine to load the .plist file which sets the `KALITE_PYTHON` environment variable in the user context so that it will be accessible in `KA-Lite.app`.

**Expected behavior:** After a successful installation the `org.learningequality.kalite.plist` file should be loaded via script so that the `KALITE_PYTHON` environment variable is set.  Remove the restart required prompt in our installer wizard.

**Checklist:**
- [x] Load the `org.learningequality.kalite.plist` via script.
- [x] Remove restart required.

**Comment by cpauya** [comment]
Fixed in #340.
