### ISSUE TITLE
Run server on system startup not working after upgrade to 0.16 (build 104)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/installers#345]
Run server on system startup not working after upgrade to 0.16 (build 104)

##### Upgrade scenario

0.15.1 > 0.16 (build 104) on Windows 7
Server was starting correctly on boot with 0.15.1 installation, independently from which user (admin or standard) logged in. 

##### Expected Behavior

If the user upgrades to 0.16 and enables `Run KA Lite on system startup` among Options in task-tray, KA Lite server should start on boot irregardless of which user logs in. 

##### Current Behavior

KALite scheduled task fails with `...The specified service does not exist. (0x800704DD)` error:

##### Screenshots

![ie11 - win7 0 16 -104 running - oracle vm virtualbox_218](https://cloud.githubusercontent.com/assets/1457929/12567480/a1143640-c3bf-11e5-8a82-b53ed979bd12.png)

![ie11 - win7 0 16 -104 running - oracle vm virtualbox_219](https://cloud.githubusercontent.com/assets/1457929/12567489/a9f1df1a-c3bf-11e5-9dec-206910422731.png)

##### Steps to reproduce

1. Install 0.15.1.
2. Upgrade to 0.16.
3. Start KA Lite.exe.
4. Activate "Run KA Lite on system startup" in KA Lite task-tray Options
5. Restart system.
6. Check the Task Scheduler.

**Comment by radinamatic** [comment]
This is what the **successful** task that runs on 0.15.1 snapshot of this VM looks like:

![ie11 - win7 netplwiz enabled password running - oracle vm virtualbox_221](https://cloud.githubusercontent.com/assets/1457929/12570300/a6bbca24-c3d6-11e5-9035-706b7d015402.png)

Run by the `SYSTEM` user **whether logged on or not**.  Maybe I missed something, but why can't we have the same in 0.16? @MCGallaspy

**Comment by radinamatic** [comment]
I did try to change several options (`Run whether logged on or not` and even adding the delay in trigger options as somebody suggested [here](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/f2bf3f60-8d65-4036-b6e6-a846a9bb6158/0x800704dd-error-while-running-a-task-as-a-standard-user?forum=windowscompatibility) ) in the scheduled task that is created by 0.16 installer, to no avail... I cannot change the account that runs the task to SYSTEM, as it is the only remaining option that seems to make the difference from 0.15 where the task works.

**Comment by radinamatic** [comment]
I'm having a meltdown with this SYSTEM user stuff... :stuck_out_tongue_closed_eyes: 

Ok, so during the upgrade we migrated the user data & content from SYSTEM user's location to current user location, and therefore we need the scheduled task to start with the current user too, right? That's what I was missing... :unamused:

**Comment by MCGallaspy** [comment]
>Ok, so during the upgrade we migrated the user data & content from SYSTEM user's location to current user location, and therefore we need the scheduled task to start with the current user too, right?

Right.

**Comment by radinamatic** [comment]
I wanted to ask this earlier, but it seemed contra-intuitive since we are trying in every way to make this thing run with the current user, and failing... Namely, is it really necessary? Could we somehow make use of SYSTEM user to start the server, since it seems the only way it's working for sure at startup (before logon), but make available that option only **AFTER** admin has created some content in it's own ./kalite folder (for new installs at least, because with upgrade there would already be some there, presumably)?

To test this proposition, I substituted the KALite task job in 0.16 snapshot (the one that tries to start the server as current user and fails), with the one from 0.15 snapshot (which uses SYSTEM user and works), and restarted the VM. Server starts OK, with both Windows admin and standard user, and uses correctly the content (langpacks at least, because I can't see the videos yet) from current user's ./kalite folder that was downloaded with 0.15 and migrated during upgrade to 0.16. What I'm unsure of is if the new content that I can't download yet, will still be stored in the same... Where was that option to change the version so I could grab 0.15 langpacks since they are not yet available for 0.16?   

So, what do you think @MCGallaspy? Could this be a way out of the tunnel?

**Comment by MCGallaspy** [comment]
> with the one from 0.15 snapshot (which uses SYSTEM user and works)

I think the crux of the matter is this. It works, but it's contrary to the user data model of KA Lite introduced in 0.13.0. It also now doesn't play nicely with the task tray program -- running the server as the SYSTEM user will not be properly reflected in the task tray. The user will still have the option to "Start the server" but it will mysteriously fail since the port is taken.

Have we firmly established that running the KA Lite server as the current user doesn't work, even when the "Start even when user is not logged in" option is enabled? I haven't personally tested it, so I can't answer either way.

**Comment by radinamatic** [comment]
> It also now doesn't play nicely with the task tray program -- running the server as the SYSTEM user will not be properly reflected in the task tray. The user will still have the option to "Start the server" but it will mysteriously fail since the port is taken.

Are we positive about this? In the test case above I wanted to look for & change the version so I can download the 0.15 langpacks, so I decided to stop the server. Since it was running as SYSTEM and not through the task tray program, I started KA Lite from the desktop shortcut, and opened it with the right-click. `Start Server` was active for about 2 seconds, and then it became unavailable while `Stop Server` became available. So task tray program does seem to register the server that is running. I will re-test this again and report back...

> Have we firmly established that running the KA Lite server as the current user doesn't work, even when the "Start even when user is not logged in" option is enabled? I haven't personally tested it, so I can't answer either way.

I poked and prodded that KALite task job changing every possible option (adding delays too, that was suggested as a possible solution somewhere), and came up empty... :crying_cat_face: 
Will continue to research!

**Comment by radinamatic** [comment]
After playing more with the previous test case on another (physical & virtual) machine, now I am positive that running the start-at-boot task as SYSTEM user does not, as @MCGallaspy noted already, play nicely with the task tray KA Lite program, at least on 0.15.1 that I have been testing.

As mentioned above, task tray program registers that server is running, but is unable to stop it - in the screenshot below I clicked several times the `Stop Server`, and it happily continued to run and would not stop even when I tried to stop it in terminal (tried running in both `C:\Program Files\KA Lite\ka-lite\bin\windows` and  `C:\Python27\Scripts`): 

![stop-server](https://cloud.githubusercontent.com/assets/1457929/12615040/9fd6eb0c-c503-11e5-8e5f-f5ed3934699d.png)

At this point I'm unsure how is server started with start-at-boot task as SYSTEM user even supposed to be stopped, ie. is the current user able to do it at all? 

I tried deactivating the `Run KA Lite at system startup` option in task-tray program, but it was running again after restart:

![stop-server2](https://cloud.githubusercontent.com/assets/1457929/12615055/b8b8c848-c503-11e5-9bca-4b964ac1cff5.png)

The only thing that eventually had the effect was disabling the task job itself in the Task Scheduler window and restarting the machine. However, using `Start Server` at this point results in a different server instance which requires the initial super-user registration and has no access to previously downloaded content.

**Comment by MCGallaspy** [comment]
> At this point I'm unsure how is server started with start-at-boot task as SYSTEM user even supposed to be stopped, ie. is the current user able to do it at all?

Prior to KA Lite 0.13.0, the answer is yes. At that time a breaking change was introduced into the application, so that the answer is no. That is indeed why we'd like the scheduled task to be run as the current user.

**Comment by MCGallaspy** [comment]
Okay @radinamatic, just want to try to clarify the expected behavior:

* 0.15.x and lower will run the start-at-boot task as the SYSTEM user (if it runs it successfully at all!)
* 0.16.x will run the start-at-boot task as the current user
* If you upgrade from a lower version to 0.16.x, then the original start-at-boot task for the SYSTEM user will remain (as I just discovered, and this is an error), *until* you enable start-at-boot as the current user through the task tray program. Then the original scheduled task as SYSTEM user will be overwritten.
* Known error: on 0.16.x the start-at-boot as current user *fails* if the "Start even when user is not logged in" option is not enabled. If you enable it, it succeeds! (I just confirmed it on W7).

Does this correspond to your experience?

**Comment by radinamatic** [comment]
@MCGallaspy Point-by-point

> 0.15.x and lower will run the start-at-boot task as the SYSTEM user (if it runs it successfully at all!)

Start-on-boot task as the SYSTEM user workes for me on all 0.13.2, 0.14.2 and 0.15.1 installs.

> 0.16.x will run the start-at-boot task as the current user

That's the plan!

> If you upgrade from a lower version to 0.16.x, then the original start-at-boot task for the SYSTEM user will remain (as I just discovered, and this is an error), until you enable start-at-boot as the current user through the task tray program. Then the original scheduled task as SYSTEM user will be overwritten.

I had to re-test this, as I wasn't positive that the original start-at-boot task for the SYSTEM user remains, as I was convinced that the KALIte task job of the previous version gets eliminated in the Uninstall step of the upgrade process. You are right, the "old" SYSTEM user task is still there, and it gets overwritten by the new current user one after the upgrade to 0.16.

> Known error: on 0.16.x the start-at-boot as current user fails if the "Start even when user is not logged in" option is not enabled. If you enable it, it succeeds! (I just confirmed it on W7).

Is this on fresh installation of 0.16 or some upgrade scenario? When I tested that after upgrading from 0.15.1, activating the "Start even when user is not logged in" did not give positive result. I'll re-check to confirm.

**Comment by radinamatic** [comment]
Update on points 2 & 3:

Retested upgrade 0.15 > 0.16 on W7. As we confirmed, the 0.15 SYSTEM user start-at-boot task is not eliminated during the uninstall, and after the install has finished, server was not running (one lone python process which is not occupying any ports):

![ie11 - win7 netplwiz enabled password running - oracle vm virtualbox_223](https://cloud.githubusercontent.com/assets/1457929/12630522/2b1aca6e-c54d-11e5-9dd8-7c70a19fc89b.png)

So I click on the desktop shortcut to open the task-tray program, and it immediately starts the server. Note the 3 python processes at this point, and that all 3 task-tray options are activated by default - **this definitely needs fixing**:

![ie11 - win7 netplwiz enabled password running - oracle vm virtualbox_224](https://cloud.githubusercontent.com/assets/1457929/12630678/dcb53502-c54d-11e5-8b6f-8280a9240ced.png)

I reopen the Task Scheduler, and the "old" task is still there, it hasn't been overwritten yet:

![ie11 - win7 netplwiz enabled password running - oracle vm virtualbox_225](https://cloud.githubusercontent.com/assets/1457929/12630763/4459a706-c54e-11e5-9e1c-59a359f7db1f.png)

I restart the system, the "old" task is still there but the server is not running. Maybe the task is corrupted somehow??? (doesn't really matter, just curious :wink:)

![ie11 - win7 netplwiz enabled password running - oracle vm virtualbox_226](https://cloud.githubusercontent.com/assets/1457929/12630858/c3395210-c54e-11e5-89cf-fa8f76944857.png)

So I open KA Lite task-tray and uncheck the `Run KA Lite at system startup` and I'm prompted to confirm that - **this is correct behavior**:

![ie11 - win7 netplwiz enabled password running - oracle vm virtualbox_227](https://cloud.githubusercontent.com/assets/1457929/12630968/537bb156-c54f-11e5-97d2-2297e76b6f6b.png)

I re-check the option and restart the system, and as expected, the "new" task is there, but the server is not running (no python process is raised). At this point I edit the task itself and select the "Start whether the user is logged in or not" option, close and restart again, but to no avail:

![ie11 - win7 netplwiz enabled password running - oracle vm virtualbox_229](https://cloud.githubusercontent.com/assets/1457929/12631198/6ed8e58a-c550-11e5-83b5-fd3e7c45e8b6.png)

Did you follow some other sequence to arrive at success at this last point? @MCGallaspy

**Comment by MCGallaspy** [comment]
In the final step, you have "Do not store password..." checked -- this will cause an error. Uncheck it, enter your password, and try again. Regarding the errored behavior above, I think it should be addressed by properly removing the SYSTEM-owned scheduled task.

**Comment by radinamatic** [comment]
Fixed in #348. Closing.
