### ISSUE TITLE
OS X package installer on Bamboo is not code signed.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#349]
**Branch** Develop

**Target** 0.16.x

**Current Behaviour** The OS X installer on Bamboo is not code signed.

**Expected Behaviour** The .pkg must be code signed.

**To replicate** Download the OS X installer from Bamboo at http://dungeon.learningequality.org:8085/browse/KL-MT16-59/artifact then install it.  You will be prompted with this dialog with the text "“KA-Lite.pkg” can’t be opened because it is from an unidentified developer.":
<img width="532" alt="screenshot 2016-01-28 19 53 29" src="https://cloud.githubusercontent.com/assets/175580/12644004/cf2804f2-c5fa-11e5-9ccb-d008a2aaa61a.png">

As an example, here are the screenshots of the VirtualBox installer that shows their .pkg is code-signed.

![screenshot 2016-01-28 20 00 22](https://cloud.githubusercontent.com/assets/175580/12643881/ee1d078c-c5f9-11e5-990a-336452f9b9b5.png)
Notice the "padlock" icon at the top-right corner of the .pkg window.  Clicking that "padlock" icon shows this panel.
![screenshot 2016-01-28 20 00 32](https://cloud.githubusercontent.com/assets/175580/12643883/f1e36690-c5f9-11e5-9a42-b005067cb088.png)

I think our `build.sh` script on Bamboo only code-signs the application and did not include the built package.

**Comment by cpauya** [comment]
[Mac OS X Gatekeeper](https://support.apple.com/en-us/HT202491) doesn't fire for unsigned .pkg if Mac OS X is in a VirtualBox VM.  

Here's a screenshot of the Mac OS X El Capitan v10.11.3 on a VirtualBox VM:
![screenshot 2016-02-02 15 45 24](https://cloud.githubusercontent.com/assets/175580/12742820/075d1f2a-c9c4-11e5-9111-d32ccc6a0e9e.png)

As per above, the .pkg is launched even when it's unsigned and the Gatekeeper security was assigned to "Mac App Store and identified developers".

To double-check if an .app or .pkg is signed, use the `pkgutil` command for the .pkg, or .app files:
* `pkgutil --check-signature KA-Lite.pkg`
* `pkgutil --check-signature KA-Lite.app`

**Comment by MCGallaspy** [comment]
Hi @cpauya, if I'm understanding this correctly, we may not wish to sign provisional builds from the build server. It might be a possible "leak" of buggy builds that appear official.

**Comment by aronasorman** [comment]
@MCGallaspy it's a bit difficult in the OSX's case, since you have to sign both the container pkg file and the files inside. So you can't build, then sign it afterwards before uploading to the pantry server.

A compromise we did was to upload only the ones that are deemed "official", although maybe @cpauya you can quickly find a way to get it signed only for official builds?

**Comment by cpauya** [comment]
Yes @MCGallaspy - good point.  But we are not going to release the provisional builds and only those in the Pantry server are the official releases.

Aside from what @aronasorman mentioned, we need to sign the .pkg and the .app for testing purposes too as I remember @EdDixon was asking about it before.

I think we can make an official build plan that sets a Bamboo env var like `IS_RELEASE` for the build script to check if to sign the .pkg and .app packages... it's cumbersome but that should work.

**Comment by cpauya** [comment]
Fixed in #349.

**Comment by cpauya** [comment]
Just a note here that we now use the `IS_KALITE_RELEASE` environment variable on `build.sh` as per #359 PR to determine if to sign the .app and the .pkg packages.  Of course the signing machine (Bamboo, CircleCI, local, etc) must have the signing certificates for this to succeed.

This will address the comment made by @MCGallaspy regarding "we may not wish to sign provisional builds from the build server".

So for the official build releases, we just create an official build plan on Bamboo and set this variable. This build plan will be based on the `master` branch of the repo.
