### ISSUE TITLE
kalite command not functioning as system command after installer process

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#35]
Affects all versions of windows, using the 0.14-develop installer, the kalite command returns kalite is not recognized as an internal or external command. expected operation is that the command is recognized and acts as any other system command on windows.

**Comment by EdDixon** [comment]
Also on MAC where the 0.14-develop installer returns command not found after successful installation. Note : this does not appear to affect the functionality of the program on the MAC platform the server and menu bar icon all seem to work as designed.

**Comment by EdDixon** [comment]
Just wanted to update in recent testing the command is still not available system wide on the MAC platform despite recent changes in the installer build (ref dungeon # 10 5/7/2015).

**Comment by MCGallaspy** [comment]
Won't fix on Windows. User is responsible for adding the script to the cmd path if desired. Please re-open the issue for OSX if desired, unsure of the status there.

**Comment by EdDixon** [comment]
Good to know, lease do be sure to add good documentation to do this on Windows systems as the  command offers a lot of utility when setup properly. It was only reported here because at that time it was a milestone for the release. 
Thanks,
