### ISSUE TITLE
Use of retrievecontentpack on post install script of OS X installer.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#358]
**Branch** develop

**Target** 0.16

**Operating System** Mac OS X

**Expected Behaviour**  Use `kalite retrievecontentpack local en path-to-en.zip` for content items.

**Current Behaviour**  We used `kalite manage init_content_items --overwrite` to populate content items.

I modified the OS X installer's post install script to replace the `kalite manage init_content_items --overwrite` with `kalite retrievecontentpack local en path-to-en.zip` -- then built the .pkg, installed on a VM, and noticed that the `~/.kalite/content_databases/content_khan_en.sqlite` on a target VM still has zero bytes.  

I replaced it with the [content.db from Pantry](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/content.db), it's about 12MB+, restarted kalite, but the sidebar didn't display anything.

**What works**

When I ran `kalite manage retrievecontentpack local en path-to-en.zip` in the target VM - it works!  The `content_khan_en.sqlite` now has 81MB+ in size.

Running the same .pkg on the target VM twice works too and it also generates the same size.

**Questions**

1. Any idea why the diff in size between the local .sqlite generated with `retrievecontentpack` versus the one in Pantry's is so big?
2. There is no tree of videos to download at Manage - Videos tab.

Setup of build (will make a PR for details of changes):

* used `ka-lite/0.16.x` branch
* used `installers/develop` branch
* build script now includes the [contentpacks/en.zip](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/en.zip) along with the [assessment.zip](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/khan_assessment.zip) when building the .pkg

On the side, the `KA-Lite.pkg` is now 691MB+ (with contentpacks/en.zip and assessment.zip) and will require at least 1.3GB+ when installed on a target Mac OS X machine.

/cc: @aronasorman

**Comment by aronasorman** [comment]
1. Looks like my upload got cut off. Check again!

**Comment by cpauya** [comment]
Thanks @aronasorman - it works now!

**Comment by radinamatic** [comment]
Just to make sure I understand correctly: .pkg installer for OSX does NOT require running `kalite manage retrievecontentpack` afterwards? Because after installing build 66 I run into one missing image in an exercise, which did appear after I run `kalite manage retrievecontentpack local en path-to-en.zip`. Or does build 66 still not include contentpack? Installer is now 410MB and says it will take 905MB on HD.

Exercise in question (`humanrunning.gif` was missing before installing contentpack):

![newton2_yosemite_10_10_5](https://cloud.githubusercontent.com/assets/1457929/13376886/0323e0d0-ddc7-11e5-9ba0-4de2c0a7f580.png)

**Comment by cpauya** [comment]
Yes @radinamatic - there's a post-install script that already runs `retrievecontentpack`.  Thanks for the tip re running `retrievecontentpack` again.  

I've made the comment about missing images at the PR https://github.com/learningequality/installers/pull/359#issuecomment-188734184

I will try to make it work today.

**Comment by radinamatic** [comment]
Just wanted to make sure if it needs to be run or not. I'll keep my eye for other missing images just in case!

**Comment by radinamatic** [comment]
Confirmed that image is missing on El Capitan, with build 66 alone @cpauya:

![newton_el_capitan](https://cloud.githubusercontent.com/assets/1457929/13397221/545eb92e-def9-11e5-89cc-2e271952fde5.png)

I guess we should be happy there is an alternative text at least... :smiley_cat: 

I'm still trying to figure out the script for [missing assessment items](https://github.com/learningequality/ka-lite/issues/4182#issuecomment-188003325) after the latest code changes, do you think there might be something that can be cooked for missing images? Not looking forward to having to check **all** the exercises for missing pics... :stuck_out_tongue_closed_eyes:

**Comment by cpauya** [comment]
I think I have the solution - I did a `manage setup` first then the `manage retrievecontentpack` and that seemed to fix it @radinamatic 

Can you please test the latest build 67 at http://dungeon.learningequality.org:8085/browse/KL-MT16-67/artifact and see if it works?

**Comment by radinamatic** [comment]
Sure... Downloading now! :+1:

**Comment by cpauya** [comment]
This is [already implemented](https://github.com/learningequality/installers/blob/develop/osx/post_installation.sh#L209) on the `develop` branch.
