### ISSUE TITLE
KA Lite Monitor app after upgrade

### ISSUE THREAD

**Issue by radinamatic** [learningequality/installers#369]
## Summary

If KA Lite Monitor app is active/open during the upgrade to 0.16, it does not get updated. Once installation finishes and user opens it from the icon in the status bar it will display the older version. When user tries to start the server the app replies with "Starting the server" but then it closes and disappears.
@cpauya 

I would recommend adding the step to installer to close the Monitor if it is opened prior to starting the actual upgrade process.

## Branch or installer

Upgrade scenario form 0.14.2 to 0.16 on OSX Yosemite.

## Screenshots

![after_upgrade_yosemite_10_10_5](https://cloud.githubusercontent.com/assets/1457929/13375654/f43e4496-dda5-11e5-93af-4fcb1a3eab69.png)

**Comment by djallado** [comment]
@radina and @cyril, I also tested the upgrade using 0.15.1 to build 80 from Dungeon on OS X Yosemite the same process above. When the installation finishes and when I refresh my browser or click on ‘’Open in Browser” it will not display anything. When I click on “Stop KA Lite”, the notification icon is blank and it will not stop I need to quit the serve and launch it again. 
The dock icon for "KA Lite" and the "KA Lite" in Applications folder were updated after the upgrade. 
For now I need to quit the server after the upgrade so that it will work properly. 

![screen shot 2016-03-18 at 11 06 07 am](https://cloud.githubusercontent.com/assets/8664071/13868204/662464c2-ed01-11e5-967f-bf739eabf17e.png)
The notification icon is blank.

**Comment by radinamatic** [comment]
@djallado Thanks for confirming this! :+1: 

@cpauya Is it possible for 0.16 installer to check & close the Monitor if it is opened prior to starting the actual upgrade process, as I suggested above? Or any other ideas you may have to prevent this issue...? :smiley:

**Comment by cpauya** [comment]
Hi @radinamatic - it's not "recommended" to just quit an application when it's loaded.  Data may get corrupted or there's no way to validate that quitting it will not corrupt anything.  

The way VirtualBox does it is to run a script before continuing the installer to check if VirtualBox is loaded and it will prompt the user to close it first.

![virtualbox](https://cloud.githubusercontent.com/assets/175580/13879096/7dbe1d9a-ed50-11e5-8f60-651aee05fb2f.gif)

I tried looking for a way to run a script before the .pkg takes the first step but can't find it as of now.  So what we do now (as @djallado suggested) is to show a "NOTE: Make sure that the KA Lite application is not loaded before continuing." at the Introduction section of the installer.  And then we check for a running "KA Lite" application during a pre-install script and fail the install if we detect it.  Here's a .gif of what I meant and how it currently works in devt.

![ka-lite-prevent-install-1](https://cloud.githubusercontent.com/assets/175580/13879616/52d6c0c0-ed53-11e5-90ab-70a292a3c210.gif)

I think this will suffice for now to prevent the issues encountered.

The ideal solution of course is to run a script like VirtualBox does to check if KA Lite is running before the installer proceeds but it's skipping me yet. :smile_cat:

**Comment by radinamatic** [comment]
@cpauya your proposal sounds like a good workaround! :+1: 
@aronasorman thoughts?

**Comment by cpauya** [comment]
Hi @radina - pls use the [build 89 at Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-89) to test this issue.

**Comment by cpauya** [comment]
We now do it like VirtualBox does it! :smile_cat: 

@radinamatic Please use [build 100 on Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-100) to test this.

**Comment by benjaoming** [comment]
this seems fixed? :)

**Comment by cpauya** [comment]
Ah yes @benjaoming, closing this now.  Thanks. 😸
