### ISSUE TITLE
Processing icon is not changing when setting the KA-Lite data path in preferences dialog.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#380]
## Summary

When setting up KA-Lite data path, the icon must change depending on the KA-Lite status. 

## Branch or installer

 - Installer: OS X build 95 from [dungeon](http://dungeon.learningequality.org/browse/KL-MT16-95)
 - Version: 0.16.x

or:

 - Branch: develop

## Screenshots
![icon12345](https://cloud.githubusercontent.com/assets/8664071/13977007/491e6a78-f100-11e5-92ea-2c15fa82319f.gif)

## How to reproduce

1. Launch `KA-Lite app`.
1. `Stop KA Lite` from menu bar
1. In the `Preferences` dialog, click on the dropdown of `KA Lite data path` and select `Desktop` then click on `Apply` button.
1. Click again the `Preferences` dialog from the menu bar.
1. In the `Preferences` dialog, click on the dropdown of `KA Lite data path`.
1. Press `Command+Shift+G` to specify the old location of `.kalite` like `/Users/yourprofile/.kalite`
1. Click the `Apply` button

**Comment by cpauya** [comment]
@amodia / @djallado Can you test [build 96 on Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-96) to check if this is fixed before I merge #378?

**Comment by amodia** [comment]
@cpauya & @djallado I tested this on build 100 from the dungeon. the processing icon work properly. 

![a-temp](https://cloud.githubusercontent.com/assets/8663934/14069821/5f0a7adc-f4d1-11e5-997d-993250851058.gif)

**Comment by cpauya** [comment]
Thanks for verifying @amodia, closing.
