### ISSUE TITLE
Learner's score is not recorded using  IE10 Windows 7.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#384]
## Summary

*Learner's score is not recorded using IE10 Windows 7, but when the learner use Google Chrome version 49.0, the score is recorded properly*

## Branch or installer

*Did issue occur on the current `develop` branch or on installation source (please specify OS and version)?*

 - Installer: Windows 
 - Version: 0.16.x using [build 208](http://dungeon.learningequality.org/browse/KL-KALITE016-208/artifact/shared/Windows-installer/KALiteSetup-0.16.0.exe)

or:

 - Branch: develop

## Screenshots

![12345](https://cloud.githubusercontent.com/assets/8664071/14135935/cee294da-f692-11e5-85c8-0b2a11075a85.gif)

## How to reproduce

1. Login as learner.
1. View a video.
1. After viewing, refresh the page. The score is not recorded.

**Comment by benjaoming** [comment]
Closing this as it's opened in the source repo.
