### ISSUE TITLE
Debian Build Script for KA-Lite Installer 

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#396]
## Summary

**Problem**

- There is no build script to automate the process to create the *.deb files.

**Objectives**   
- To create a debian build script that automate the docker image to produce *.deb files.
- Create a signed deb file.
- Run the build script in the bamboo server.

## Branch or installer

 - Installer: `Debian`
 - Branch: `master`

**Comment by benjaoming** [comment]
Duplicate of #149
