### ISSUE TITLE
Pyrun failed to install setuptools.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/installers#401]
## Summary

Pyrun failed to install `setuptools`  when building KA-Lite OS X installer.

## Branch or installer

 - Installer: `OS X`
 - Version: `master`

## Screenshots

![screen shot 2016-06-09 at 4 24 15 am](https://cloud.githubusercontent.com/assets/4099119/15909702/1d2941cc-2dfa-11e6-9fc5-9df52d3a8dac.png)

## How to reproduce

1. Navigate to `~/installers/osx/`
1. Run `./build.sh`
1. Notice that during installing eGenix PyRun the `setuptools` fail to install.

**Comment by benjaoming** [comment]
Is this issue fixed now that the PRs have been merged?

**Comment by arceduardvincent** [comment]
Yeah this issue is already fixed.
