### ISSUE TITLE
Current develop MAC installer fails to work as designed with content  

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#44]
The installation procedure for those testing on MAC's is this:
First remove all previous installation of KA Lite by following the following steps:

1. delete the "KA-Lite Monitor.app" from the Applications folder
2. from an open terminal env | grep KA will reveal the env. variables used which need to be unset.
unset KALITE_DIR and unset KALITE_PYTHON
3. rm ~/Library/Preferences/FLE-KA-Lite-Monitor.plist
4. reboot at this point all traces of the previously installed KA Lite application should have been removed.
5. Download current MAC develop installer http://dungeon.learningequality.org:8085/browse/KL-KALITE014-19 with content from dungeon should be 300+ MB less indicates the build does not have that content (which is also known not to have this issue) hopefully newer builds will find this issue closed.
6. open the file downloaded and then drag the KA-Lite Monitor.app to the provided applications folder
7. IMPORTANT! Make absolutely sure all terminals are closed at this point allowing the installer to set the needed variables in the environment.
8. Go to Launchpad and click on KA-Lite Monitor
9. IMPORTANT there is a suspected race condition between the menubar icon becoming available and the preferences dialog box opening which must have data entered on first run DO NOT START THE SERVER PRIOR TO COMPLETING THE PREFERENCES DIALOG

To complete installation and replicate this issue:

10. goto the menubar icon and click start kalite all other options will become unavailable at this point.
11. You can wait for the server to become available but I have given it over an hour before reporting this issue and will find that the page on localhost is not available ...
12. open a terminal and run kalite status will report start failed check logs
13. from terminal issue kalite stop will return that it is already in the stopped state
14. issue kalite start which seems to launch an installation procedure instead of just starting the server you will notice many items being copied to the installation folder.  
15. after completion the terminal will report that the server is available on 127.0.0.1:8008 and your local IP
16. open a browser to either of those addresses and be greeted by the home page informing you no administration account is available and also to login with the administration account you just created? 
17. attempt to login with the account you created which fails
18. follow the procedure from terminal "kalite manage createsuperuser" and complete prompts
19. try again to login to the server.. success but not the user experience we are shooting for here!

**Comment by aronasorman** [comment]
Closed as non-issue. This was before we were aware that @MCGallaspy's DB-backed assessment items has been merged.
