### ISSUE TITLE
Windows installer should use setup.py (setuptools)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#48]
Hi @ruimalheiro 

Hopefully this will be helpful for you and in the future will help to reduce the responsibility of the Windows installer.

After installing Python + setuptools, which I guess is bundled with the installer, you can install the ka-lite-static zip package which can be found on pypi:

https://pypi.python.org/pypi/ka-lite-static

In the zip, which you can bundle with the installer, you find the typical `setup.py` script. It's installed by running `setup.py install` as all distributed Python packages are.

After installing it, if you can make `C:\Python27\Scripts` and `C:\Python27\` appear in the Windows path, we can have `kalite` in the command line. ( more info here: http://docs.python-guide.org/en/latest/starting/install/win/ )

**Comment by MCGallaspy** [comment]
I'm debating whether we need to change the windows installer to use setuptools, given that it works ok for now. That said, if we do revisit the InnoSetup script for any reason, it's probably worthwhile to refactor it to use `setup.py` in order to consolidate the responsibility in one place and avoid code with duplicate functionality and language proliferation in the project. (I'm looking at you, PascalScript.)

**Comment by aronasorman** [comment]
I think it's better to have all the installers install using the same mechanism, as that leads to less special-casing between platforms.

**Comment by MCGallaspy** [comment]
> I think it's better to have all the installers install using the same mechanism, as that leads to less special-casing between platforms.

I agree, we need to figure out where this lies in our ordinal priority list.

**Comment by benjaoming** [comment]
I don't know if this is useful, but this is how debian packaging works:

setup.py is invoked to install in a relative directory at build time. So setup.py is actually not run while installing the .deb, but while building it!

This is perfectly fine, as the .deb format is intended to contain files to be placed on the target system which are then managed by dpkg.

Would a similar install builder for Windows exist? Otherwise, would it be possible to put all of the Windows installation logic in a separate setup_windows.py that invokes/imports setup.py and thus contain everything for Windows in the original source tree without a separate software project? Recall that a setup.py can be made into a setup.exe with distutils...

**Comment by MCGallaspy** [comment]
Could be useful, seems like we could do essentially the same thing on Windows -- it's just a matter of rewriting the scripts and debugging them. We also manage some upgrade scenarios through InnoSetup, so we'd have to figure out how we wish to handle that.
