### ISSUE TITLE
MAC installer should use setup.py

### ISSUE THREAD

**Issue by benjaoming** [learningequality/installers#49]
Hi @cpauya 

This is kind of a boiler plate issue from the similar issue on the windows installer :)

But hopefully this will be helpful for you and in the future will help to reduce the responsibility of the Mac installer.

After installing Python + setuptools, which I guess is bundled with the installer, you can install the ka-lite-static tarball which can be found on pypi:

https://pypi.python.org/pypi/ka-lite-static

It's installed by running setup.py install as all distributed Python packages are.

After that, users should have access to the `kalite` command directly in their Terminal.

You can also install ka-lite directly from PyPi: `pip install ka-lite` (you have to add --pre currently because we have no stable releases) or `pip install ka-lite` (static version with no external deps).

**Comment by cpauya** [comment]
Thanks for the heads up @benjaoming. Will be taking a look at setuptools
next.
