### ISSUE TITLE
Current develop Git Installer is not installable on Debian systems

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#52]
I would suppose this would apply to all Debian based systems including Ubuntu which surprises me as I know a lot of development is currently ongoing in Ubuntu to begin with but running a GIT installation using ( bin/kalite manage setup) as was working in previous develop installations from a freshly pulled develop branch this morning on the latest debian resulted in a failure with the linked traceback. https://s3.amazonaws.com/uploads.hipchat.com/86198/1302220/PV9hID8syoOeyTT/kalite-setup-traceback.txt

**Comment by benjaoming** [comment]
This was fixed in the alpha1 release
