### ISSUE TITLE
Windows task tray program does nothing

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/installers#56]
I built the installer as per instructions using the `develop` branch of ka-lite and tried installing on Windows 7. The task tray icon is unable to start the server; clicking it does not cause the "Start server" option to become disabled (which is what I expected). `kalite start` works fine. @ruimalheiro @cpauya I'm assigning myself, but if someone more savvy decides to tackle this I would not object.

**Comment by cpauya** [comment]
Hi @MCGallaspy - @amodia encountered this issue a few days ago.  

I think it's because the windows app is using the deprecated scripts instead of the `bin/kalite` executable as you reported on #25.

**Comment by MCGallaspy** [comment]
Yes, I do believe that's why. We'll need to edit the GUI to use `bin/kalite` instead of the deprecated scripts.

**Comment by amodia** [comment]
@MCGallaspy I'm starting to edit the `GUI` to use the `bin/kalite` commands when starting and stoping the ka-lite server.

This is part of the `GUI` source that needs to modify.
![screen shot 2015-06-10 at 4 36 29 pm](https://cloud.githubusercontent.com/assets/8663934/8078261/04146d04-0f8f-11e5-98db-d3a64b4ba8a2.png)
![screen shot 2015-06-10 at 4 37 07 pm](https://cloud.githubusercontent.com/assets/8663934/8078265/0901bac4-0f8f-11e5-9018-003ebf557975.png)

**Comment by MCGallaspy** [comment]
@amodia @ruimalheiro 
I think what we need to do is replace the calls to `runShellScript` that @amodia has indicated with a new function with the same return type (`bool`) called (let's say) `runPythonScript`, which makes a call to [CreateProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx) to invoke the Python interpreter. Does that seem reasonable? Also, @ruimalheiro, any tips on buliding `KA Lite.exe`? I am a but a humble n00b to windows programming.

**Comment by MCGallaspy** [comment]
Okay, after reading up on [ShellExecuteEx](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762154%28v=vs.85%29.aspx) more, I think it would just be possible to call `kalite.bat` using the same `runShellScript` function... which is nice and easy.
