### ISSUE TITLE
Windows GUI does not pop up when app icon is clicked

### ISSUE THREAD

**Issue by jtamiace** [learningequality/installers#60]
Windows 8.1

The icons do appear in the task tray though, but stack up multiple icons depending on how many times the app icon is clicked: 

![task tray](https://cloud.githubusercontent.com/assets/6668144/8141806/eb532f82-1121-11e5-85c2-d209e6a1ec4e.png)

**Comment by MCGallaspy** [comment]
Can you elaborate on what the expected behavior is? My understanding is that the task-tray icon is the only component of the windows GUI, did you expect something else to happen?

**Comment by MCGallaspy** [comment]
Also, using a fairly recent installer, I'm not able to make multiple icons appear by clicking on the icon. Closing.
