### ISSUE TITLE
Unknown command "migrate" 

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#61]
**Branch:** Master
**Expected behavior:** It must have a migrate command to run the `ka-lite` migration. 
**Steps to reproduce:**
 1. Required `windows xp sp3` Operating systems.
 2. Build `kalitesetup.exe` using `make.vbs`.
 3. Install the `kalitesetup.exe`.
 4. Open Command line and manually run `kalite start` at `program files\ka-lite\bin` directory.

![screen shot 2015-06-15 at 3 48 49 pm](https://cloud.githubusercontent.com/assets/8663934/8155362/22455f64-1376-11e5-9d61-47130cee2b96.png)

**Comment by MCGallaspy** [comment]
@amodia did you follow the `Instructions to download pip dependency zip files using Windows` in `windows/README.md`?

**Comment by amodia** [comment]
@MCGallaspy Yeah, I followed that instructions and I was able to run the `ka-lite server` using the `gui` by adding the `KALITE_DIR` to my `windows environment variable`.

Here's a screenshot.

![screen shot 2015-06-17 at 6 21 22 pm](https://cloud.githubusercontent.com/assets/8663934/8204816/041720d2-151e-11e5-9819-e3da15fc41d6.png)
![screen shot 2015-06-17 at 6 20 18 pm](https://cloud.githubusercontent.com/assets/8663934/8204810/fc0e3c18-151d-11e5-97fa-b361d9961e84.png)

**Comment by MCGallaspy** [comment]
@amodia I don't understand, are you saying you built the installer again, this time following the instructions to download the pip dependencies? Or that you followed those instructions the first time?

Are you saying that you get the `CommandError` while still being able to start the server using the gui? Or that "adding the KALITE_DIR to my windows environment variable" fixed both issues?

And can you describe what you mean exactly by adding KALITE_DIR to your windows environment variable? Did you create a new registry value, or something else?

**Comment by amodia** [comment]
@MCGallaspy Apologize for the confusion. I build the installer using `make.vbs` and I follow the instruction to download the pip dependencies. If I add the `KALITE_DIR` to my [windows environment variable](http://www.computerhope.com/issues/ch000549.htm) this will fixed the `command error`.

These are the steps I've done to run the `kalite server` using `gui`.
 1. Follow the steps to download the pip dependencies zip files in `windows/README.md`. 
 2. Build the `KaliteSetup.exe` using `make.vbs`.
 3. Install the`KaliteSetup.exe`.
 4. Set the `KALITE_DIR` in windows environment variables, refer to the screenshot bellow.
![screen shot 2015-06-18 at 9 58 12 am](https://cloud.githubusercontent.com/assets/8663934/8222770/fb07dc00-15a1-11e5-8df9-340c8062f2ea.png)
 5. Start the `kalite server` using the `gui`.

**Comment by djallado** [comment]
Hi @amodia and @MCGallaspy!

I Build windows installer in Windows XP by following the instructions from the windows installer readme.
After installing, I had noticed that it works the same as windows 7 installer except the notifications are not displaying in XP. 

I put screenshots below:
![menu](https://cloud.githubusercontent.com/assets/8664071/8381636/680b1dee-1c5f-11e5-9a07-f0c2690b870b.png)
![login](https://cloud.githubusercontent.com/assets/8664071/8381641/782af1ea-1c5f-11e5-8dc2-77fe0dd39e24.png)

**Comment by cpauya** [comment]
This issue is non-existent on current branches, please re-open if not so.
