### ISSUE TITLE
Can not Log Into KA-Lite post Install MAC

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#63]
On Develop branch 6/18/2015 after installation and completion of the preferences for su login credentials unable to login to the site using those same credentials with error; user unknown?  Expected behavior would be to login without any problems obviously. In further testing it was discovered that the required .plist for the application did not exist in the expected folder.

**Comment by cpauya** [comment]
Hi @EdDixon - I've been having this same error, here's the screenshot:
![screenshot 2015-06-22 19 10 28](https://cloud.githubusercontent.com/assets/175580/8280710/6661e6a8-1912-11e5-84ce-1c6f6dd4763b.png)

Taking the hint from the [kalite/distributed/management/commands/setup.py](https://github.com/learningequality/ka-lite/blob/develop/kalite/distributed/management/commands/setup.py#L170) source, I was able to login using the following:
* username == `settings.INSTALL_ADMIN_USERNAME` or `getpass.getuser()` (without the "_" or "-") characters
* password == the password in your .plist

For my laptop, I was able to login as username==cyril (my username), password=a (the password on the preferences dialog).

I don't know yet why it's not using username passed to it by the user preferences dialog.
