### ISSUE TITLE
Windows installer does not create database

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/installers#71]
@EdDixon I think has reported this, and the failure to create a superuser is probably also a symptom of the issue here. Need to check out the function defined in `KaliteSetupScript.iss`.

**Comment by MCGallaspy** [comment]
Also, we need to exclude the file ` .KALITE_SOURCE_DIR`

**Comment by cpauya** [comment]
@MCGallaspy Perhaps this is related to [format of arguments on setup management command](https://github.com/learningequality/ka-lite/issues/3939)?

In summary, the windows installer need to use `python manage setup --noinput --username=value --password=value` format.

Although @benjaoming [had a PR addressing](https://github.com/learningequality/ka-lite/pull/3940) the `--key value` format - but may be worth a look also.

**Comment by MCGallaspy** [comment]
@cpauya yup, that was it
