### ISSUE TITLE
Debian package description is cut off when installing on Ubuntu

### ISSUE THREAD

**Issue by jamalex** [learningequality/installers#77]
![image](https://cloud.githubusercontent.com/assets/618416/8488041/ef367106-20c4-11e5-9145-2625109a8397.png)

Not sure whether there's a limit in the Ubuntu Software Center displayed length, or if it's getting trimmed earlier in the process.

**Comment by jamalex** [comment]
If it's possible to change the name of the package from `ka-lite` to `KA Lite` that might be worthwhile as well?

**Comment by benjaoming** [comment]
Weird, your version to be putting the description below the name, while mine does this:

![screenshot from 2015-07-03 02 16 18](https://cloud.githubusercontent.com/assets/374612/8490461/9cc91d50-2129-11e5-925b-36aa4318ea02.png)

I don't know exactly how to get the name displayed correctly, it might be some meta data missing in the .deb package.

**Comment by benjaoming** [comment]
Alpha3:

![screenshot from 2015-07-06 21 06 24](https://cloud.githubusercontent.com/assets/374612/8530852/e4329584-2423-11e5-9640-4d1d20dbaa65.png)
