### ISSUE TITLE
Rename "Super User" to "Admin" in the login modal

### ISSUE THREAD

**Issue by radinamatic** [learningequality/installers#79]
Linux installer (maybe Mac too, haven't tried that one) asks for "Super User" to be created upon install. It should be rephrased to "Create Admin" rather than "Create Super User", specially since that account is called 'Admin' in the KA Lite documentation.

**Comment by rtibbles** [comment]
@radinamatic this is a KA Lite issue, please open it there :)

**Comment by radinamatic** [comment]
In Spanish we would say "que lío"... ;)
Will reopen in KA Lite!
