### ISSUE TITLE
Bundle pre-migrated empty database into installers to reduce load time

### ISSUE THREAD

**Issue by jamalex** [learningequality/installers#80]
The first time the server is started, it takes a long time to load (see https://github.com/learningequality/installers/issues/78), and the longest-running task is the database migration. When the setup was run from the command line, at least the user saw that something was happening, but now it just seems like it's hanging.

If we can bundle a pre-migrated (but empty) database in (like we do in the Android app), this should cut down the load time very significantly. Steps to create such a database:

- Delete any existing database
- Run `bin/kalite manage syncdb` and then `bin/kalite manage migrate --merge`
- Do *not* run `setup`, or start the server (as that will start adding data)

**Comment by benjaoming** [comment]
This is a great idea! What about shipping it as a data file in the source directory? It seems useful to all new deployments...

**Comment by MCGallaspy** [comment]
Now done in the KA Lite. See https://github.com/learningequality/ka-lite/pull/4656. Empty db included if it exists, which it does if you build a distributable using our handy-dandy makefile.

**Comment by benjaoming** [comment]
Just to clarify: This won't happen until 0.16, right? At least, that's how it is for the .debs where it's the ka-lite source dist that's responsible for this....

**Comment by MCGallaspy** [comment]
Right.
