### ISSUE TITLE
There's a bug that always shows the user preferences dialog.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#91]
**Branch:** `Master` (OS X Installer)
 The `User preferences` dialog always shows because database location has changed.

**Expected Behavior:**
`User preferences` dialog will disappear after clicking the `Apply` button.

**Current Behavior:**
The `User preferences` dialog always show after clicking the `Apply` button.

**Steps to reproduce:**

1. Load `KA-Lite Monotor` app.
2. Set `username` and `password` in `User preferences` dialog and click `Apply`.
![screen shot 2015-07-10 at 12 03 28 pm](https://cloud.githubusercontent.com/assets/8664071/8612000/2a06aaca-26fc-11e5-9dc4-373c419004a5.png)
3. Notice that the `User preferences` dialog is alway shown until the `Start KA Lite` menu is clickable.

**Screenshots below:**
![screen shot 2015-07-10 at 1 13 41 pm](https://cloud.githubusercontent.com/assets/8664071/8612611/d234016c-2705-11e5-89a9-c69d6953a3c5.png)
![screen shot 2015-07-10 at 1 14 57 pm](https://cloud.githubusercontent.com/assets/8664071/8612615/df61a10a-2705-11e5-96c3-7a7807f2f0c1.png)
![screen shot 2015-07-10 at 1 23 23 pm](https://cloud.githubusercontent.com/assets/8664071/8612690/3fb011d0-2707-11e5-846a-e794f2cde12f.png)

**Comment by cpauya** [comment]
This is because the location of the database has changed, so when the .app is loaded and the database is not found, it will prompt for the user preferences dialog.

@djallado Can you add this to your ToDos?
