### ISSUE TITLE
ka-lite-static is not installed when I install latest build from dungeon on Windows Installer.

### ISSUE THREAD

**Issue by djallado** [learningequality/installers#94]
**Branch:** `Master (Windows Installer Build 183)`

**Expected Behavior:** `ka-lite-static` should be installed when I install the latest build from dungeo. Like in the screenshot:
![fornow](https://cloud.githubusercontent.com/assets/8664071/8649247/eedceb70-299a-11e5-927b-ddf49db56717.png)

**Current Behavior:** `ka-lite-static` is not installed after I install the latest build. 
Here's the screenshot if I pip freeze:
![latest](https://cloud.githubusercontent.com/assets/8664071/8649265/37d8cd44-299b-11e5-909d-36f5da9ac89b.png)

**Steps to reproduce:**
1. Install `IE810- Windows7` in `virtual box`
2. Download windows installer **build 183** from `dungeon`
3. Install `KALiteSetup-0.14.0.exe` *(latest installer downloaded from dungeon)*
4. Follow `KA Lite Setup Wizard`
5. Launch `KA Lite`
6. Select `Computer` from the `Start menu`
7. Choose `System Properties` from the context menu
8. Click `Advanced system settings` > Advanced tab
9. Click on `Environment Variables`, under `System Variables`, find `PATH`, and click on it.
10. In the `Edit windows`, modify `PATH` by adding `;C:\Python27;C:\Python27\Scripts`. and click ok.
11. Reopen `Command prompt` window, and type `pip freeze`. There's no `ka-lite-static` like in the screenshot:
![latest](https://cloud.githubusercontent.com/assets/8664071/8649467/2e1a0fc8-299d-11e5-8fbf-d098be9a88bd.png)

To make it work, I have to install `kalite-static` manually like screenshot below:
![after_install_static](https://cloud.githubusercontent.com/assets/8664071/8647905/b4932580-298e-11e5-80f0-fdac0acf00e6.png)

Then when I launch KA-Lite, it works fine. I can now download videos like in a screenshot below:
![123](https://cloud.githubusercontent.com/assets/8664071/8648239/976ce6fa-2991-11e5-9ba8-f43295cb0dd5.png)

**Comment by aronasorman** [comment]
Known bug, and something I want to fix. Has something to do with wine, as the build in windows itself works. Somehow running InnoSetup through wine only bundles a small subset of the assessment items.

**Comment by MCGallaspy** [comment]
@aronasorman are you commenting on a different issue here? If you are using the Windows installer, I do not think that ka-lite-static needs to be installed for the application to work.

**Comment by benjaoming** [comment]
The bulk of this should be gone, from @radinamatic 's feedback it seems there might still be an issue for Windows XP, but we have no such reports as of now.. so I'm going to assume it's also fixed on XP.

Feel free to open up a new issue @radinamatic if this is something you still see on XP!

Great work all :)
