### ISSUE TITLE
KA-Lite 13 to 14 upgrade creates error on student Login

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#96]
Windows XP

While testing version 0.13 to 0.14 now in development I discovered that logging in as a student creates an unexpected error "no such column main_exerciselog.liatest_activity_timestamp". However the admin account seemed to work fine? To replicate, install 0.13 create a student account do some exercises and then install 14 (develop) over the current install. You will also notice Python is not updated in this process despite being bundled. Afterwards logging in as admin appears fine using the modal system however, logging out and then logging in as the student previously created will provide the error.
![2015-07-13_16-36-07](https://cloud.githubusercontent.com/assets/4349806/8662625/fa6bf916-297e-11e5-8b90-b969bc0653c6.png)

**Comment by MCGallaspy** [comment]
Is this issue specific to XP? Did you notice it on other versions of windows @EdDixon?

**Comment by EdDixon** [comment]
I have confirmed the error now in Windows 7, and Windows 8.1. ALL VERSIONS of windows appear to be affected? Also as noted here in the XP test, On those other versions of windows python is not being updated despite being bundled with a newer version, 2.7.10. I am not sure but I would think the expected behavior here is that the version of python being used for KA-Lite be updated to the bundled version?

**Comment by EdDixon** [comment]
I have verified that by adding the /Python27/Scripts folder to the systems environment path does resolve this issue on XP and provides a system wide working kalite command. Which before could only be used by calling its full path with the .bat extension.

**Comment by EdDixon** [comment]
To replicate and test the path fix for XP after having installed 13 and then created and used a student account to complete some of the assessments upgrade to 14 and then:

1) Right click on My Computer
2) Choose Properties
3) Click on the Advanced Tab
4) Click on the the Environments Variables Button
5) In the System Variables settings section scroll down and select the Path variable
6) Click the Edit button 
7) Very carefully in the Edit System Variable dialog box Variable value text box (not to change anything in the current string) navigate to the end of the variable value and add without quotation marks the following "; C:\Python27\Scripts" The semicolon is important! 
8) In the command prompt type kalite manage setup
9) When asked to keep the database file type "yes" and press enter
10) WHen asked to download assessment items now type "no" and press enter
11) When asked have you already loaded the assessment items package type no and press enter allowing process to complete


To test some of the new functionality now provided:
1) Start the server using the gui icon in the task tray
2) From the gui select "Load in Browser" 
3) Login with the student account you previously used choosing the default Facility (You will notice this error no longer exists and are brought to the proper landing page showing where you left off in the assessments).
4) Open a command prompt
5)Type kalite status from any location on the drive including the default (you will be notified that KA Lite is started and the addresses it is available on)
6)  From the command prompt type kalite stop and press enter (You will notice that the gui now reports the server has stopped a page refresh in the browser will verify)
7) From the command prompt type kalite start
8) If using chrome you will notice the browser is now on the home page of the site (other browsers may need to refresh, you will also notice the command prompt is no llonger available due to the logging in daemon mode
9) from the GUI select "Stop Server" (You will notice the server is stopped and the command prompt becomes available!

Slight variations of this to enter the path variable are required for each version of windows but in all cases tested (windows XP and WIndows 8.1, so far) this results in the kalite command and gui functionality working together on windows as designed!

**Comment by EdDixon** [comment]
Confirmed that python is now being updated during the ka-lite upgrade using latest development installer.

**Comment by MCGallaspy** [comment]
Great! Did you also confirm whether the title issue still exists?

**Comment by EdDixon** [comment]
I did not get see this specific issue logging in as the student using that upgrade ("no such column main_exerciselog.liatest_activity_timestamp") but have not tested all versions yet? I do feel it is most likely resolved!  \o/

**Comment by EdDixon** [comment]
Edited the path procedure for XP to reflect changes to the current windows installer which eliminated several required steps!

**Comment by MCGallaspy** [comment]
Closing unless you report that the title issues still exists, @EdDixon.
